// ============================================================================
// WASM Main - {{NAME}}
// ============================================================================
// WebAssembly version using raylib + emscripten.
// Uses emscripten_set_main_loop for proper browser integration.
// Generated by labelle-cli. Customize as needed.
// ============================================================================

const std = @import("std");
const builtin = @import("builtin");
const engine = @import("labelle-engine");

// Detect if we're building for emscripten/WASM
const is_wasm = builtin.os.tag == .emscripten;

pub const GameId = u64;

// Register your prefabs here
pub const Prefabs = engine.PrefabRegistry(.{
    // Example: .player = @import("prefabs/player.zon"),
});

// Register your components here
pub const Components = engine.ComponentRegistry(struct {
    pub const Position = engine.Position;
    pub const Sprite = engine.Sprite;
    pub const Shape = engine.Shape;
    pub const Text = engine.Text;
});

// Register your scripts here
pub const Scripts = engine.ScriptRegistry(struct {
    // Example: pub const player_movement = @import("scripts/player_movement.zig");
});

pub const Loader = engine.SceneLoader(Prefabs, Components, Scripts);

// Inline scene definition (or import from scenes/ directory)
pub const initial_scene = .{
    .name = "main",
    .entities = .{
        // Example entity with shape
        .{
            .components = .{
                .Position = .{ .x = 400, .y = 300 },
                .Shape = .{
                    .shape = .{ .circle = .{ .radius = 30 } },
                    .color = .{ .r = 100, .g = 150, .b = 255, .a = 255 },
                },
            },
        },
    },
};

// Get the scene type from Loader.load's return type using compile-time introspection
const SceneType = blk: {
    const load_fn_type = @TypeOf(Loader.load);
    const fn_info = @typeInfo(load_fn_type).@"fn";
    const return_type = fn_info.return_type.?;
    // It's an error union, get the payload type
    break :blk @typeInfo(return_type).error_union.payload;
};

// Compile-time embedded configuration (no file I/O in WASM)
const WINDOW_WIDTH = 800;
const WINDOW_HEIGHT = 600;
const WINDOW_TITLE = "{{TITLE}}";
const TARGET_FPS = 60;

const Game = engine.Game;

// Emscripten-specific code (only compiled for WASM target)
const emscripten = if (is_wasm) struct {
    extern fn emscripten_set_main_loop_arg(
        func: *const fn (?*anyopaque) callconv(.c) void,
        arg: ?*anyopaque,
        fps: c_int,
        simulate_infinite_loop: c_int,
    ) void;
} else struct {};

// Global state for emscripten callback (only used in WASM)
const GameState = struct {
    game: *Game,
    scene: *SceneType,
    allocator: std.mem.Allocator,
};
var game_state: ?GameState = null;

// Frame callback for emscripten (only compiled for WASM)
fn frameCallback(_: ?*anyopaque) callconv(.c) void {
    if (game_state) |*state| {
        const dt = state.game.getDeltaTime();
        state.scene.update(dt);
        state.game.getPipeline().sync(state.game.getRegistry());

        const re = state.game.getRetainedEngine();
        re.beginFrame();
        re.render();
        re.endFrame();
    }
}

pub fn main() !void {
    // Use page allocator for WASM compatibility
    const allocator = std.heap.page_allocator;

    var game = try Game.init(allocator, .{
        .window = .{
            .width = WINDOW_WIDTH,
            .height = WINDOW_HEIGHT,
            .title = WINDOW_TITLE,
            .target_fps = TARGET_FPS,
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    });
    game.fixPointers();

    const ctx = engine.SceneContext.init(&game);

    var scene = try Loader.load(initial_scene, ctx);

    if (is_wasm) {
        // WASM: Store state for callback and use emscripten's main loop
        game_state = .{
            .game = &game,
            .scene = &scene,
            .allocator = allocator,
        };

        // Use emscripten's main loop - this never returns in WASM
        // fps=0 means use requestAnimationFrame, simulate_infinite_loop=1 prevents return
        emscripten.emscripten_set_main_loop_arg(frameCallback, null, 0, 1);

        // This code is never reached in WASM mode
        scene.deinit();
        game.deinit();
    } else {
        // Native: Use traditional game loop
        while (game.isRunning()) {
            const dt = game.getDeltaTime();
            scene.update(dt);
            game.getPipeline().sync(game.getRegistry());

            const re = game.getRetainedEngine();
            re.beginFrame();
            re.render();
            re.endFrame();
        }

        scene.deinit();
        game.deinit();
    }
}
