//! iOS Build Configuration - Auto-generated by labelle CLI
//!
//! Usage:
//!   zig build ios       # Build for iOS device
//!   zig build ios-sim   # Build for iOS simulator
//!
//! Note: The sokol Zig module is accessed through engine.sokol to avoid
//! module conflicts. The sokol dependency is only used for linking sokol_clib.
//! The ios_main.zig template uses `const sokol = engine.sokol;`

const std = @import("std");

/// Get iOS SDK path using xcrun
fn getIosSdkPath(b: *std.Build, sdk_name: []const u8) ?[]const u8 {
    const result = std.process.Child.run(.{
        .allocator = b.allocator,
        .argv = &.{ "xcrun", "--sdk", sdk_name, "--show-sdk-path" },
    }) catch return null;
    defer b.allocator.free(result.stdout);
    defer b.allocator.free(result.stderr);
    if (result.term == .Exited and result.term.Exited == 0) {
        const path = std.mem.trim(u8, result.stdout, &std.ascii.whitespace);
        return b.allocator.dupe(u8, path) catch null;
    }
    return null;
}

pub fn build(b: *std.Build) void {
    const optimize = b.standardOptimizeOption(.{});

    const app_name = "test_project";

    // Detect iOS SDK path using xcrun (required for C header includes)
    // Use simulator SDK as it works for both device and simulator builds
    // (simulator SDK is a superset that includes both architectures)
    if (getIosSdkPath(b, "iphonesimulator")) |sdk_path| {
        b.sysroot = sdk_path;
    } else if (getIosSdkPath(b, "iphoneos")) |sdk_path| {
        b.sysroot = sdk_path;
    }

    // iOS Device Target
    const ios_device_target = b.resolveTargetQuery(.{
        .cpu_arch = .aarch64,
        .os_tag = .ios,
    });

    // iOS Simulator Target (Apple Silicon Macs)
    // Use apple_a14 to enable NEON SIMD features required by box2d physics
    const ios_sim_target = b.resolveTargetQuery(.{
        .cpu_arch = .aarch64,
        .os_tag = .ios,
        .abi = .simulator,
        .cpu_model = .{ .explicit = &std.Target.aarch64.cpu.apple_a14 },
    });

    // iOS SDK paths (use non-versioned paths which are symlinks to current SDK)
    const ios_device_sdk = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk";
    const ios_sim_sdk = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk";

    // iOS Device build
    // sokol dependency for linking C library (dont_link_system_libs=true for iOS)
    const ios_sokol = b.dependency("sokol", .{
        .target = ios_device_target,
        .optimize = optimize,
        .dont_link_system_libs = true,
    });

    // Configure sokol for iOS - add SDK include paths for C header compilation
    const ios_sokol_clib = ios_sokol.artifact("sokol_clib");
    ios_sokol_clib.root_module.addSystemIncludePath(.{ .cwd_relative = ios_device_sdk ++ "/usr/include" });
    ios_sokol_clib.root_module.addSystemFrameworkPath(.{ .cwd_relative = ios_device_sdk ++ "/System/Library/Frameworks" });
    ios_sokol_clib.root_module.addSystemFrameworkPath(.{ .cwd_relative = ios_device_sdk ++ "/System/Library/SubFrameworks" });

    // Engine provides sokol through engine.sokol (re-exported to avoid module conflicts)
    const ios_engine = b.dependency("labelle-engine", .{
        .target = ios_device_target,
        .optimize = optimize,
    });

    // Create main module from project's main.zig (contains registries and scenes)
    const ios_main_mod = b.createModule(.{
        .root_source_file = b.path("../main.zig"),
        .target = ios_device_target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "labelle-engine", .module = ios_engine.module("labelle-engine") },
        },
    });

    const ios_exe = b.addExecutable(.{
        .name = app_name,
        .root_module = b.createModule(.{
            .root_source_file = b.path("../ios_main.zig"),
            .target = ios_device_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "labelle-engine", .module = ios_engine.module("labelle-engine") },
                .{ .name = "main", .module = ios_main_mod },
            },
        }),
    });

    // Link sokol C library (for iOS Metal backend)
    ios_exe.linkLibrary(ios_sokol.artifact("sokol_clib"));
    ios_exe.linkLibC();

    // Add iOS Device SDK framework search path
    ios_exe.root_module.addFrameworkPath(.{ .cwd_relative = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" });

    // Link iOS frameworks
    ios_exe.root_module.linkFramework("Foundation", .{});
    ios_exe.root_module.linkFramework("UIKit", .{});
    ios_exe.root_module.linkFramework("Metal", .{});
    ios_exe.root_module.linkFramework("MetalKit", .{});
    ios_exe.root_module.linkFramework("AudioToolbox", .{});
    ios_exe.root_module.linkFramework("AVFoundation", .{});

    const ios_step = b.step("ios", "Build for iOS device");
    ios_step.dependOn(&ios_exe.step);
    ios_step.dependOn(&b.addInstallArtifact(ios_exe, .{}).step);

    // iOS Simulator build
    const sim_sokol = b.dependency("sokol", .{
        .target = ios_sim_target,
        .optimize = optimize,
        .dont_link_system_libs = true,
    });

    // Configure sokol for iOS Simulator - add SDK include paths for C header compilation
    const sim_sokol_clib = sim_sokol.artifact("sokol_clib");
    sim_sokol_clib.root_module.addSystemIncludePath(.{ .cwd_relative = ios_sim_sdk ++ "/usr/include" });
    sim_sokol_clib.root_module.addSystemFrameworkPath(.{ .cwd_relative = ios_sim_sdk ++ "/System/Library/Frameworks" });
    sim_sokol_clib.root_module.addSystemFrameworkPath(.{ .cwd_relative = ios_sim_sdk ++ "/System/Library/SubFrameworks" });

    const sim_engine = b.dependency("labelle-engine", .{
        .target = ios_sim_target,
        .optimize = optimize,
    });

    // Create main module from project's main.zig (contains registries and scenes)
    const sim_main_mod = b.createModule(.{
        .root_source_file = b.path("../main.zig"),
        .target = ios_sim_target,
        .optimize = optimize,
        .imports = &.{
            .{ .name = "labelle-engine", .module = sim_engine.module("labelle-engine") },
        },
    });

    const sim_exe = b.addExecutable(.{
        .name = app_name ++ "_sim",
        .root_module = b.createModule(.{
            .root_source_file = b.path("../ios_main.zig"),
            .target = ios_sim_target,
            .optimize = optimize,
            .imports = &.{
                .{ .name = "labelle-engine", .module = sim_engine.module("labelle-engine") },
                .{ .name = "main", .module = sim_main_mod },
            },
        }),
    });

    // Link sokol C library (for iOS Simulator Metal backend)
    sim_exe.linkLibrary(sim_sokol.artifact("sokol_clib"));
    sim_exe.linkLibC();

    // Add iOS Simulator SDK framework search path
    sim_exe.root_module.addFrameworkPath(.{ .cwd_relative = "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks" });

    sim_exe.root_module.linkFramework("Foundation", .{});
    sim_exe.root_module.linkFramework("UIKit", .{});
    sim_exe.root_module.linkFramework("Metal", .{});
    sim_exe.root_module.linkFramework("MetalKit", .{});
    sim_exe.root_module.linkFramework("AudioToolbox", .{});
    sim_exe.root_module.linkFramework("AVFoundation", .{});

    const sim_step = b.step("ios-sim", "Build for iOS simulator");
    sim_step.dependOn(&sim_exe.step);
    sim_step.dependOn(&b.addInstallArtifact(sim_exe, .{}).step);
}
