const std = @import("std");
const project_config = @import("project_config.zig");
const config = @import("config.zig");
const asm_cache = @import("asm_cache.zig");

/// Write labelle.lock into the project root.
///
/// `.cli_version` is a HIGH-WATER mark, not "whoever wrote last" (#353):
/// an existing stamp NEWER than this binary is carried through unchanged.
/// The gate (`enforceCliNotStale`) already refuses to build such a project,
/// so the only way here is the deliberate `--allow-older-cli` /
/// `LABELLE_ALLOW_OLDER_CLI=1` override — and the incident's compounding
/// half was exactly that a stale binary restamped the lock DOWN to its own
/// version, which would silently disarm the gate for every later run. One
/// override must not permanently un-gate the project. To genuinely move a
/// project back to an older CLI, edit (or delete) the lock's
/// `.cli_version` line.
pub fn writeLockFile(allocator: std.mem.Allocator, project_dir: []const u8, cfg: project_config.ProjectConfig) !void {
    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    const w = &aw.writer;

    try w.writeAll(
        \\// labelle.lock — resolved dependency versions
        \\// Generated by labelle-cli. Commit this file to git.
        \\.{
        \\
    );

    const lock_path = try std.fs.path.join(allocator, &.{ project_dir, "labelle.lock" });
    defer allocator.free(lock_path);

    // High-water `.cli_version` — see the doc comment above. `previous`
    // owns the bytes `keep_version` points into, so it stays alive until
    // after the print.
    const previous: ?[]u8 = std.Io.Dir.cwd().readFileAlloc(config.globalIo(), lock_path, allocator, .limited(1024 * 1024)) catch null;
    defer if (previous) |p| allocator.free(p);
    const keep_version: []const u8 = blk: {
        const prev = previous orelse break :blk project_config.CLI_VERSION;
        const stamped = lockCliVersion(prev) orelse break :blk project_config.CLI_VERSION;
        break :blk if (isLockNewer(stamped, project_config.CLI_VERSION)) stamped else project_config.CLI_VERSION;
    };
    try w.print("    .cli_version = \"{s}\",\n", .{keep_version});
    try w.print("    .resolved = .{{\n", .{});
    try w.print("        .core = .{{ .version = \"{s}\" }},\n", .{cfg.core_version});
    try w.print("        .engine = .{{ .version = \"{s}\" }},\n", .{cfg.engine_version});
    try w.print("        .gfx = .{{ .version = \"{s}\" }},\n", .{cfg.gfx_version});
    try w.print("        .labelle = .{{ .version = \"{s}\" }},\n", .{cfg.labelle_version});
    // NOTE: `backend` (both `name` and `platform`) is intentionally not persisted.
    // Both fields are invocation state, not resolved dependencies:
    //   - `platform` is the build target from CLI args (e.g. `labelle android run`).
    //   - `name` is forced by the same CLI commands — `ios`/`android` pin `.sokol`
    //     while a desktop run uses whatever the project config picks (could be
    //     `.raylib`).
    // Writing either caused the lock file to flap on every cross-deploy. The lock
    // file is a manifest of resolved package versions, not build-target state.

    if (cfg.ecs != .mock) {
        try w.print("        .ecs = .{{ .name = \"{s}\" }},\n", .{@tagName(cfg.ecs)});
    }
    // GUI plugin (#222). Post-#217 the assembler owns GUI *resolution*
    // (it reads `gui.labelle`, validates bridges, populates
    // `cfg.resolved_gui`), so `cfg.resolved_gui` is always null on the
    // CLI side. To keep the GUI from silently vanishing from
    // labelle.lock, the CLI re-derives the plugin name here from the
    // declared `gui:` reference in project.labelle:
    //   - `cfg.resolved_gui` is preferred when present (future-proof: if
    //     the assembler ever reports it back, this picks it up).
    //   - otherwise `guiLockName` reads the plugin's `gui.labelle`
    //     manifest `name` (the same authoritative field the assembler
    //     uses) when the plugin directory is locally resolvable, and
    //     falls back to a name derived from the declared reference.
    if (cfg.resolved_gui) |gui| {
        try w.print("        .gui = .{{ .name = \"{s}\" }},\n", .{gui.name});
    } else if (cfg.gui) |gui_ref| {
        const name = guiLockName(allocator, project_dir, cfg, gui_ref);
        defer if (name.owned) allocator.free(name.value);
        try w.print("        .gui = .{{ .name = \"{s}\" }},\n", .{name.value});
    }

    try w.writeAll("    },\n");

    if (cfg.plugins.len > 0) {
        try w.writeAll("    .plugins = .{\n");
        for (cfg.plugins) |plugin| {
            try w.print("        .{{ .name = \"{s}\", .repo = \"{s}\", .version = \"{s}\" }},\n", .{
                plugin.name, plugin.repo, plugin.version,
            });
        }
        try w.writeAll("    },\n");
    }

    try w.writeAll("}\n");

    try std.Io.Dir.cwd().writeFile(config.globalIo(), .{
        .sub_path = lock_path,
        .data = aw.written(),
    });
}

/// A GUI plugin name destined for the lock file, plus whether the buffer
/// is heap-owned (and therefore must be freed by the caller).
const GuiName = struct {
    value: []const u8,
    owned: bool,
};

/// Minimal subset of the `gui.labelle` manifest — only the `name` field,
/// which is the authoritative GUI plugin name the assembler also keys on.
/// `ignore_unknown_fields` lets the rest of the manifest evolve freely.
const GuiManifestName = struct {
    name: []const u8,
};

/// Re-derive the GUI plugin name for the lock file from the declared
/// `gui:` reference in project.labelle.
///
/// Preferred source is the plugin's own `gui.labelle` manifest `name`
/// field — the same value the assembler resolves into `resolved_gui`.
/// The lock file is written during `labelle generate`, which runs after
/// `labelle install` has populated the package cache, so the CLI can read
/// the manifest directly for every reference the assembler can resolve:
///   - `gui.path`   → `<project_dir>/<path>` (always local).
///   - `gui.plugin` → a `.plugins` entry. Local repos (`local:` / `@`)
///     resolve to their path; remote repos resolve to their cached
///     directory under `~/.labelle/packages/plugins/<repo>/<version>`
///     (the same path `cache.resolvePlugin` produces).
///
/// `gui.package` / `gui.url` are not resolvable here: the assembler's own
/// `gui_resolve.zig` does not resolve those forms either (it is a TODO —
/// it only supports `.path` and `.plugin`), so there is no shared cache
/// path to read. Those fall back to a best-effort label derived from the
/// declared reference. See `resolveGuiPluginDir`.
///
/// When the manifest is genuinely unreadable (cache miss, missing file,
/// parse error) the name falls back to a best-effort label derived from
/// the declared reference so the GUI still appears in the lock.
fn guiLockName(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    cfg: project_config.ProjectConfig,
    gui_ref: project_config.GuiPlugin,
) GuiName {
    if (resolveGuiPluginDir(allocator, project_dir, cfg, gui_ref)) |plugin_dir| {
        defer allocator.free(plugin_dir);
        if (readGuiManifestName(allocator, plugin_dir)) |name| {
            return .{ .value = name, .owned = true };
        }
    }
    // Fallback: a label derived from the declared reference. Borrowed
    // slices from `cfg` (no allocation, no free).
    return .{ .value = fallbackGuiName(gui_ref), .owned = false };
}

/// Resolve the GUI plugin directory.
///
/// Handles every reference form the assembler's `gui_resolve.zig` can
/// resolve, using the same resolution scheme:
///   - `gui.path`   → `<project_dir>/<path>`.
///   - `gui.plugin` → a `.plugins` entry. Local repos resolve to their
///     `local:` / `@` path; remote repos resolve to their cached
///     directory in `~/.labelle/packages/plugins/<repo>/<version>`.
///     Remote plugins are present there because the lock file is written
///     after `labelle install` has populated the cache.
///
/// Returns null for `gui.package` / `gui.url`: the assembler does not
/// resolve those forms yet (`gui_resolve.zig:resolvePluginDir` rejects
/// them with `error.GuiPluginResolutionNotSupported`), so there is no
/// authoritative cache path to read — the caller falls back. If the
/// assembler ever gains `.package` / `.url` resolution, this should be
/// extended to mirror whatever cache path it lands them at.
fn resolveGuiPluginDir(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    cfg: project_config.ProjectConfig,
    gui_ref: project_config.GuiPlugin,
) ?[]const u8 {
    if (gui_ref.path) |rel_path| {
        return std.fs.path.resolve(allocator, &.{ project_dir, rel_path }) catch null;
    }
    if (gui_ref.plugin) |name| {
        const dep = cfg.getPlugin(name) orelse return null;
        if (dep.isLocal())
            return std.fs.path.resolve(allocator, &.{ project_dir, dep.localPath() }) catch null;
        // Remote plugin — resolve from the package cache the same way
        // `cache.resolvePlugin` does. `labelle install` ran before the
        // lock file is written, so the plugin is already cached here.
        return asm_cache.resolveRemotePluginDir(allocator, dep.repo, dep.version) catch null;
    }
    return null;
}

/// Read the `name` field from `<plugin_dir>/gui.labelle`. Returns a
/// heap-owned copy, or null if the manifest cannot be used.
///
/// A *missing* manifest is silent and expected (e.g. a remote plugin not
/// yet fetched). But a manifest that exists yet fails to read or parse
/// is a real fault: the lock file then silently records a *derived*
/// fallback name that can diverge from the assembler-resolved identity.
/// Such failures emit a warning so the resulting lockfile drift is
/// diagnosable instead of mysterious.
fn readGuiManifestName(allocator: std.mem.Allocator, plugin_dir: []const u8) ?[]const u8 {
    const manifest_path = std.fs.path.join(allocator, &.{ plugin_dir, "gui.labelle" }) catch return null;
    defer allocator.free(manifest_path);

    const raw = std.Io.Dir.cwd().readFileAlloc(
        config.globalIo(),
        manifest_path,
        allocator,
        .limited(64 * 1024),
    ) catch |err| {
        // FileNotFound is expected (plugin not present) — stay silent.
        // Anything else (permissions, I/O error, size limit) is a real
        // fault worth surfacing.
        if (err != error.FileNotFound) {
            std.debug.print(
                "labelle: warning: could not read GUI manifest '{s}': {s} — labelle.lock .gui name falls back to a derived value\n",
                .{ manifest_path, @errorName(err) },
            );
        }
        return null;
    };
    defer allocator.free(raw);

    const raw_z = allocator.dupeZ(u8, raw) catch return null;
    defer allocator.free(raw_z);

    const manifest = std.zon.parse.fromSliceAlloc(
        GuiManifestName,
        allocator,
        raw_z,
        null,
        .{ .ignore_unknown_fields = true },
    ) catch |err| {
        // The manifest file exists but won't parse — warn so the
        // fallback name in labelle.lock is not silently misleading.
        std.debug.print(
            "labelle: warning: could not parse GUI manifest '{s}': {s} — labelle.lock .gui name falls back to a derived value\n",
            .{ manifest_path, @errorName(err) },
        );
        return null;
    };
    defer std.zon.parse.free(allocator, manifest);

    if (manifest.name.len == 0) {
        std.debug.print(
            "labelle: warning: GUI manifest '{s}' has an empty .name — labelle.lock .gui name falls back to a derived value\n",
            .{manifest_path},
        );
        return null;
    }
    return allocator.dupe(u8, manifest.name) catch null;
}

/// Best-effort GUI name from the declared reference when the manifest
/// cannot be read. Borrows slices from the reference — no allocation.
fn fallbackGuiName(gui_ref: project_config.GuiPlugin) []const u8 {
    if (gui_ref.plugin) |name| return name;
    if (gui_ref.path) |path| return lastPathComponent(path);
    if (gui_ref.package) |pkg| return pkg;
    if (gui_ref.url) |url| return lastPathComponent(url);
    return "unknown";
}

/// Trailing path/URL component, stripping any trailing slashes.
fn lastPathComponent(s: []const u8) []const u8 {
    var end = s.len;
    while (end > 0 and (s[end - 1] == '/' or s[end - 1] == '\\')) end -= 1;
    var start = end;
    while (start > 0 and s[start - 1] != '/' and s[start - 1] != '\\') start -= 1;
    if (start == end) return s;
    return s[start..end];
}

// ── Tests ────────────────────────────────────────────────────────────

const testing = std.testing;

test "lastPathComponent: trailing component of a relative path" {
    try testing.expectEqualStrings("imgui-plugin", lastPathComponent("../plugins/imgui-plugin"));
}

test "lastPathComponent: strips trailing slash" {
    try testing.expectEqualStrings("nuklear", lastPathComponent("libs/nuklear/"));
}

test "lastPathComponent: bare name passes through" {
    try testing.expectEqualStrings("gui", lastPathComponent("gui"));
}

test "fallbackGuiName: prefers the declared plugin reference name" {
    const ref = project_config.GuiPlugin{ .plugin = "my-gui", .path = "../whatever" };
    try testing.expectEqualStrings("my-gui", fallbackGuiName(ref));
}

test "fallbackGuiName: derives from path when no plugin reference" {
    const ref = project_config.GuiPlugin{ .path = "../plugins/imgui-plugin" };
    try testing.expectEqualStrings("imgui-plugin", fallbackGuiName(ref));
}

test "fallbackGuiName: derives from package, then url" {
    try testing.expectEqualStrings("zig-nuklear", fallbackGuiName(.{ .package = "zig-nuklear" }));
    try testing.expectEqualStrings("repo", fallbackGuiName(.{ .url = "https://example.com/repo" }));
}

test "fallbackGuiName: unknown when nothing is declared" {
    try testing.expectEqualStrings("unknown", fallbackGuiName(.{}));
}

test "guiLockName: reads authoritative name from gui.labelle manifest" {
    const alloc = testing.allocator;

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.writeFile(config.globalIo(), .{
        .sub_path = "gui.labelle",
        .data =
        \\.{
        \\    .name = "imgui",
        \\    .rendering = .raw_backend,
        \\}
        ,
    });

    const plugin_dir = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
    defer alloc.free(plugin_dir);

    // project_dir is unused for an absolute-style relative `path` join here;
    // pass "." so the resolved dir is exactly `plugin_dir`.
    const cfg = project_config.ProjectConfig{ .name = "t" };
    const name = guiLockName(alloc, ".", cfg, .{ .path = plugin_dir });
    defer if (name.owned) alloc.free(name.value);

    try testing.expect(name.owned);
    try testing.expectEqualStrings("imgui", name.value);
}

test "guiLockName: falls back to reference name when manifest is missing" {
    const alloc = testing.allocator;

    var tmp = testing.tmpDir(.{}); // empty dir — no gui.labelle
    defer tmp.cleanup();
    const plugin_dir = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
    defer alloc.free(plugin_dir);

    const cfg = project_config.ProjectConfig{ .name = "t" };
    const name = guiLockName(alloc, ".", cfg, .{ .path = plugin_dir });
    defer if (name.owned) alloc.free(name.value);

    // No manifest → borrowed fallback derived from the path's last component.
    try testing.expect(!name.owned);
    try testing.expectEqualStrings(lastPathComponent(plugin_dir), name.value);
}

test "guiLockName: remote plugin with empty cache falls back to reference name" {
    const alloc = testing.allocator;
    // `gui.plugin` referencing a remote (non-local) plugin whose package
    // cache directory does not exist (not installed): resolution finds no
    // manifest, so it falls back to the declared reference name.
    var tmp = testing.tmpDir(.{}); // empty — no packages/ tree
    defer tmp.cleanup();
    const cache_root = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
    defer alloc.free(cache_root);
    asm_cache.setCacheRootOverride(cache_root);
    defer asm_cache.clearCacheRootOverride();

    const cfg = project_config.ProjectConfig{
        .name = "t",
        .plugins = &.{.{ .name = "remote-gui", .repo = "github.com/acme/g", .version = "1.0.0" }},
    };
    const name = guiLockName(alloc, ".", cfg, .{ .plugin = "remote-gui" });
    defer if (name.owned) alloc.free(name.value);

    try testing.expect(!name.owned);
    try testing.expectEqualStrings("remote-gui", name.value);
}

test "guiLockName: remote plugin reads authoritative name from package cache" {
    const alloc = testing.allocator;
    // A remote `gui.plugin` reference, fetched into the package cache by
    // `labelle install`. The lock file must record the authoritative
    // `gui.labelle` `name`, not the local `.plugins` alias.
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    const cache_root = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
    defer alloc.free(cache_root);
    asm_cache.setCacheRootOverride(cache_root);
    defer asm_cache.clearCacheRootOverride();

    // Lay out the cached plugin exactly where cache.resolvePlugin expects:
    //   <cache-root>/packages/plugins/<repo>/<version>/gui.labelle
    const repo = "github.com/acme/imgui-gui";
    const version = "2.3.0";
    const rel_dir = try std.fs.path.join(alloc, &.{ "packages", "plugins", repo, version });
    defer alloc.free(rel_dir);
    try tmp.dir.createDirPath(config.globalIo(), rel_dir);
    const rel_manifest = try std.fs.path.join(alloc, &.{ rel_dir, "gui.labelle" });
    defer alloc.free(rel_manifest);
    try tmp.dir.writeFile(config.globalIo(), .{
        .sub_path = rel_manifest,
        .data = ".{ .name = \"imgui\", .rendering = .raw_backend }",
    });

    const cfg = project_config.ProjectConfig{
        .name = "t",
        // The `.plugins` alias ("remote-gui") deliberately differs from the
        // authoritative manifest name ("imgui").
        .plugins = &.{.{ .name = "remote-gui", .repo = repo, .version = version }},
    };
    const name = guiLockName(alloc, ".", cfg, .{ .plugin = "remote-gui" });
    defer if (name.owned) alloc.free(name.value);

    try testing.expect(name.owned);
    try testing.expectEqualStrings("imgui", name.value);
}

test "writeLockFile-style: gui entry is emitted from a declared path reference" {
    const alloc = testing.allocator;

    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.writeFile(config.globalIo(), .{
        .sub_path = "gui.labelle",
        .data = ".{ .name = \"nuklear\", .rendering = .render_interface }",
    });
    const plugin_dir = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
    defer alloc.free(plugin_dir);

    const cfg = project_config.ProjectConfig{ .name = "t", .gui = .{ .path = plugin_dir } };

    // Re-derive exactly what writeLockFile would print for the `.gui` line.
    try testing.expect(cfg.resolved_gui == null); // CLI never populates this
    const gui_ref = cfg.gui.?;
    const name = guiLockName(alloc, ".", cfg, gui_ref);
    defer if (name.owned) alloc.free(name.value);
    try testing.expectEqualStrings("nuklear", name.value);
}

// --- Stale-CLI gate (#353) ------------------------------------------------

/// True when `lock_version` is strictly newer than `current_version`.
/// Unparseable versions never trip the gate — an old hand-edited lock
/// must not brick the CLI.
pub fn isLockNewer(lock_version: []const u8, current_version: []const u8) bool {
    const lock_v = std.SemanticVersion.parse(lock_version) catch return false;
    const cur_v = std.SemanticVersion.parse(current_version) catch return false;
    return std.SemanticVersion.order(lock_v, cur_v) == .gt;
}

/// Extract the TOP-LEVEL `.cli_version = "X"` from a labelle.lock's
/// bytes. A line-wise scan with brace-depth tracking, not a zon parse: the
/// file is CLI-generated and the line shape is stable (`writeLockFile`
/// above), and a scan can't be broken by resolved-set fields this CLI
/// version doesn't know. Depth anchoring + comment skipping keep a
/// `.cli_version` inside a comment, string, or nested unknown field from
/// tripping a false stale-CLI refusal.
pub fn lockCliVersion(lock_bytes: []const u8) ?[]const u8 {
    const key = ".cli_version = \"";
    var depth: usize = 0;
    var lines = std.mem.splitScalar(u8, lock_bytes, '\n');
    while (lines.next()) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (std.mem.startsWith(u8, trimmed, "//")) continue;
        if (depth == 1 and std.mem.startsWith(u8, trimmed, key)) {
            const rest = trimmed[key.len..];
            const end = std.mem.indexOfScalar(u8, rest, '"') orelse return null;
            if (end == 0) return null;
            return rest[0..end];
        }
        for (trimmed) |c| {
            if (c == '{') depth += 1;
            if (c == '}') depth -|= 1;
        }
    }
    return null;
}

/// The guard against a stale binary silently mis-building a modern
/// project (#353): a labelle.lock written by a NEWER CLI means this
/// binary may not understand everything the project relies on — the
/// incident case being per-atlas `.astc_block`, which an older CLI
/// skipped via `ignore_unknown_fields` and then encoded every atlas at
/// the old global block size. No error anywhere, visibly broken art.
///
/// Returns `error.StaleCli` after printing an actionable message.
/// Two equivalent escape hatches downgrade it to a warning, for
/// deliberately building with an older CLI:
///   - `allow_older` — the `--allow-older-cli` flag (#353 names it), set
///     by the command's own parser (`generate`/`build`/`run`/`astc`);
///   - `LABELLE_ALLOW_OLDER_CLI=1` (exactly "1") — the env form, which
///     also covers commands whose parsers don't take the flag and is the
///     usable shape for CI.
/// A missing lock or one without a parseable version never trips the
/// gate; a lock that EXISTS but cannot be read fails closed — an
/// unverifiable lock is not a verified one.
pub fn enforceCliNotStale(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    allow_older: bool,
) error{StaleCli}!void {
    const lock_path = std.fs.path.join(allocator, &.{ project_dir, "labelle.lock" }) catch return;
    defer allocator.free(lock_path);
    const bytes = std.Io.Dir.cwd().readFileAlloc(config.globalIo(), lock_path, allocator, .limited(1024 * 1024)) catch |err| switch (err) {
        error.FileNotFound => return, // no lock, nothing to verify against
        else => {
            std.debug.print(
                "labelle: could not read labelle.lock ({t}) — refusing to build against an unverifiable lock; fix or delete the file\n",
                .{err},
            );
            return error.StaleCli;
        },
    };
    defer allocator.free(bytes);

    const lock_version = lockCliVersion(bytes) orelse return;
    if (!isLockNewer(lock_version, project_config.CLI_VERSION)) return;

    const override: ?[]u8 = config.globalEnviron().getAlloc(allocator, "LABELLE_ALLOW_OLDER_CLI") catch null;
    defer if (override) |o| allocator.free(o);
    const env_override = override != null and std.mem.eql(u8, override.?, "1");
    if (allow_older or env_override) {
        std.debug.print(
            "labelle: warning: labelle.lock was written by labelle v{s}, this binary is v{s} — proceeding because {s} is set\n",
            .{ lock_version, project_config.CLI_VERSION, if (allow_older) "--allow-older-cli" else "LABELLE_ALLOW_OLDER_CLI" },
        );
        return;
    }
    std.debug.print(
        \\labelle: this project's labelle.lock was written by labelle v{s},
        \\         but this binary is v{s} — an older CLI can silently
        \\         mis-build a newer project (unknown project.labelle fields
        \\         are skipped; e.g. per-atlas `.astc_block` falls back to a
        \\         global block size and mangles the art).
        \\
        \\  Fix:      upgrade this binary to v{s} or newer.
        \\  Override: labelle <command> --allow-older-cli
        \\            (or LABELLE_ALLOW_OLDER_CLI=1 labelle <command>)
        \\
    , .{ lock_version, project_config.CLI_VERSION, lock_version });
    return error.StaleCli;
}

test "isLockNewer: strictly newer trips, equal and older do not" {
    try std.testing.expect(isLockNewer("1.61.1", "1.59.0"));
    try std.testing.expect(!isLockNewer("1.59.0", "1.59.0"));
    try std.testing.expect(!isLockNewer("1.59.0", "1.61.1"));
    // Unparseable on either side never trips the gate.
    try std.testing.expect(!isLockNewer("garbage", "1.59.0"));
    try std.testing.expect(!isLockNewer("1.61.1", "garbage"));
}

test "lockCliVersion: extracts the stamped version" {
    const lock =
        \\// labelle.lock — resolved dependency versions
        \\.{
        \\    .cli_version = "1.61.1",
        \\    .resolved = .{},
        \\}
    ;
    try std.testing.expectEqualStrings("1.61.1", lockCliVersion(lock).?);
    try std.testing.expect(lockCliVersion("no version here") == null);
}

test "lockCliVersion: only the top-level field counts" {
    // A comment and a NESTED unknown field both carry decoys; the real
    // stamp is the depth-1 line.
    const lock =
        \\// the old stamp was .cli_version = "9.9.9", ignore it
        \\.{
        \\    .resolved = .{
        \\        .future_thing = .{ .cli_version = "8.8.8" },
        \\    },
        \\    .cli_version = "1.61.1",
        \\}
    ;
    try std.testing.expectEqualStrings("1.61.1", lockCliVersion(lock).?);

    // Decoys alone (comment + nested) must not produce a version at all.
    const decoys_only =
        \\// .cli_version = "9.9.9"
        \\.{
        \\    .resolved = .{
        \\        .future_thing = .{ .cli_version = "8.8.8" },
        \\    },
        \\}
    ;
    try std.testing.expect(lockCliVersion(decoys_only) == null);
}

/// Write a labelle.lock stamped with `version` into a fresh tmp dir and
/// return the dir path the gate should be pointed at (cwd-relative, the
/// same shape the other tmp-dir tests here use). Caller frees.
fn stampedLockDir(alloc: std.mem.Allocator, tmp: *std.testing.TmpDir, version: []const u8) ![]u8 {
    const body = try std.fmt.allocPrint(
        alloc,
        "// labelle.lock — resolved dependency versions\n.{{\n    .cli_version = \"{s}\",\n    .resolved = .{{}},\n}}\n",
        .{version},
    );
    defer alloc.free(body);
    try tmp.dir.writeFile(config.globalIo(), .{ .sub_path = "labelle.lock", .data = body });
    return std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &tmp.sub_path });
}

test "enforceCliNotStale: a lock from a newer CLI is a hard error" {
    const alloc = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    // 99.0.0 is unreachably newer than any real CLI_VERSION, so this
    // test can't rot into a no-op as the CLI is released.
    const dir = try stampedLockDir(alloc, &tmp, "99.0.0");
    defer alloc.free(dir);

    try std.testing.expectError(error.StaleCli, enforceCliNotStale(alloc, dir, false));
}

test "enforceCliNotStale: --allow-older-cli downgrades the refusal to a warning" {
    const alloc = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const dir = try stampedLockDir(alloc, &tmp, "99.0.0");
    defer alloc.free(dir);

    // Same lock, same binary — the flag is the only difference.
    try std.testing.expectError(error.StaleCli, enforceCliNotStale(alloc, dir, false));
    try enforceCliNotStale(alloc, dir, true);
}

test "enforceCliNotStale: an equal-or-older lock, and no lock at all, pass" {
    const alloc = std.testing.allocator;

    var same = std.testing.tmpDir(.{});
    defer same.cleanup();
    const same_dir = try stampedLockDir(alloc, &same, project_config.CLI_VERSION);
    defer alloc.free(same_dir);
    try enforceCliNotStale(alloc, same_dir, false);

    var older = std.testing.tmpDir(.{});
    defer older.cleanup();
    const older_dir = try stampedLockDir(alloc, &older, "0.0.1");
    defer alloc.free(older_dir);
    try enforceCliNotStale(alloc, older_dir, false);

    // No labelle.lock: nothing to verify against, never a refusal.
    var empty = std.testing.tmpDir(.{});
    defer empty.cleanup();
    const empty_dir = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &empty.sub_path });
    defer alloc.free(empty_dir);
    try enforceCliNotStale(alloc, empty_dir, false);
}

test "enforceCliNotStale: a newer lock's version is not restamped down by the gate" {
    // The incident's compounding half: the stale binary rewrites the lock
    // to its OWN version. The gate runs BEFORE any lock write
    // (`pipeline.run` calls it at the top; `writeLockFile` happens after
    // the build), so a refused invocation must leave the stamp untouched
    // — otherwise a second run would sail through against a downgraded
    // lock. Asserted on the bytes.
    const alloc = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const dir = try stampedLockDir(alloc, &tmp, "99.0.0");
    defer alloc.free(dir);

    try std.testing.expectError(error.StaleCli, enforceCliNotStale(alloc, dir, false));

    const after = try tmp.dir.readFileAlloc(config.globalIo(), "labelle.lock", alloc, .limited(64 * 1024));
    defer alloc.free(after);
    try std.testing.expectEqualStrings("99.0.0", lockCliVersion(after).?);
}

test "writeLockFile: a newer stamp is a high-water mark, not overwritten" {
    const alloc = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();
    const dir = try stampedLockDir(alloc, &tmp, "99.0.0");
    defer alloc.free(dir);

    // The `--allow-older-cli` path: this (older) binary is allowed to
    // build, and then rewrites the lock. The stamp must NOT come down to
    // CLI_VERSION — that is what silently disarmed the gate for every
    // later run in the incident.
    try writeLockFile(alloc, dir, .{ .name = "t" });
    const after = try tmp.dir.readFileAlloc(config.globalIo(), "labelle.lock", alloc, .limited(64 * 1024));
    defer alloc.free(after);
    try std.testing.expectEqualStrings("99.0.0", lockCliVersion(after).?);
}

test "writeLockFile: an older or absent stamp becomes this CLI's version" {
    const alloc = std.testing.allocator;

    var older = std.testing.tmpDir(.{});
    defer older.cleanup();
    const older_dir = try stampedLockDir(alloc, &older, "0.0.1");
    defer alloc.free(older_dir);
    try writeLockFile(alloc, older_dir, .{ .name = "t" });
    const bumped = try older.dir.readFileAlloc(config.globalIo(), "labelle.lock", alloc, .limited(64 * 1024));
    defer alloc.free(bumped);
    try std.testing.expectEqualStrings(project_config.CLI_VERSION, lockCliVersion(bumped).?);

    // No pre-existing lock at all: plain stamp.
    var fresh = std.testing.tmpDir(.{});
    defer fresh.cleanup();
    const fresh_dir = try std.fs.path.join(alloc, &.{ ".zig-cache", "tmp", &fresh.sub_path });
    defer alloc.free(fresh_dir);
    try writeLockFile(alloc, fresh_dir, .{ .name = "t" });
    const written = try fresh.dir.readFileAlloc(config.globalIo(), "labelle.lock", alloc, .limited(64 * 1024));
    defer alloc.free(written);
    try std.testing.expectEqualStrings(project_config.CLI_VERSION, lockCliVersion(written).?);
}
