const std = @import("std");
const project_config = @import("project_config.zig");
const config = @import("config.zig");

/// Write labelle.lock into the project root.
pub fn writeLockFile(allocator: std.mem.Allocator, project_dir: []const u8, cfg: project_config.ProjectConfig) !void {
    var aw = std.Io.Writer.Allocating.init(allocator);
    defer aw.deinit();
    const w = &aw.writer;

    try w.writeAll(
        \\// labelle.lock — resolved dependency versions
        \\// Generated by labelle-cli. Commit this file to git.
        \\.{
        \\
    );

    try w.print("    .cli_version = \"{s}\",\n", .{project_config.CLI_VERSION});
    try w.print("    .resolved = .{{\n", .{});
    try w.print("        .core = .{{ .version = \"{s}\" }},\n", .{cfg.core_version});
    try w.print("        .engine = .{{ .version = \"{s}\" }},\n", .{cfg.engine_version});
    try w.print("        .gfx = .{{ .version = \"{s}\" }},\n", .{cfg.gfx_version});
    try w.print("        .labelle = .{{ .version = \"{s}\" }},\n", .{cfg.labelle_version});
    // NOTE: `backend` (both `name` and `platform`) is intentionally not persisted.
    // Both fields are invocation state, not resolved dependencies:
    //   - `platform` is the build target from CLI args (e.g. `labelle android run`).
    //   - `name` is forced by the same CLI commands — `ios`/`android` pin `.sokol`
    //     while a desktop run uses whatever the project config picks (could be
    //     `.raylib`).
    // Writing either caused the lock file to flap on every cross-deploy. The lock
    // file is a manifest of resolved package versions, not build-target state.

    if (cfg.ecs != .mock) {
        try w.print("        .ecs = .{{ .name = \"{s}\" }},\n", .{@tagName(cfg.ecs)});
    }
    // KNOWN GAP (#222): post-#217, GUI resolution moved into the
    // assembler's `generate` subcommand, so the CLI never populates
    // `cfg.resolved_gui` — this branch is currently dead and the
    // `.gui` entry is omitted from labelle.lock. Restoring it needs
    // the assembler to report the resolved GUI back to the CLI.
    if (cfg.resolved_gui) |gui| {
        try w.print("        .gui = .{{ .name = \"{s}\" }},\n", .{gui.name});
    }

    try w.writeAll("    },\n");

    if (cfg.plugins.len > 0) {
        try w.writeAll("    .plugins = .{\n");
        for (cfg.plugins) |plugin| {
            try w.print("        .{{ .name = \"{s}\", .repo = \"{s}\", .version = \"{s}\" }},\n", .{
                plugin.name, plugin.repo, plugin.version,
            });
        }
        try w.writeAll("    },\n");
    }

    try w.writeAll("}\n");

    const lock_path = try std.fs.path.join(allocator, &.{ project_dir, "labelle.lock" });
    defer allocator.free(lock_path);

    try std.Io.Dir.cwd().writeFile(config.globalIo(), .{
        .sub_path = lock_path,
        .data = aw.written(),
    });
}
