const std = @import("std");
const gen = @import("generator");

/// Write labelle.lock into the project root.
pub fn writeLockFile(allocator: std.mem.Allocator, project_dir: []const u8, cfg: gen.ProjectConfig) !void {
    var buf = std.ArrayList(u8){};
    defer buf.deinit(allocator);
    const w = buf.writer(allocator);

    try w.writeAll(
        \\// labelle.lock — resolved dependency versions
        \\// Generated by labelle-cli. Commit this file to git.
        \\.{
        \\
    );

    try w.print("    .cli_version = \"{s}\",\n", .{gen.CLI_VERSION});
    try w.print("    .resolved = .{{\n", .{});
    try w.print("        .core = .{{ .version = \"{s}\" }},\n", .{cfg.core_version});
    try w.print("        .engine = .{{ .version = \"{s}\" }},\n", .{cfg.engine_version});
    try w.print("        .gfx = .{{ .version = \"{s}\" }},\n", .{cfg.gfx_version});
    try w.print("        .labelle = .{{ .version = \"{s}\" }},\n", .{cfg.labelle_version});
    try w.print("        .backend = .{{ .name = \"{s}\", .platform = \"{s}\" }},\n", .{ @tagName(cfg.backend), @tagName(cfg.platform) });

    if (cfg.ecs != .mock) {
        try w.print("        .ecs = .{{ .name = \"{s}\" }},\n", .{@tagName(cfg.ecs)});
    }
    if (cfg.resolved_gui) |gui| {
        try w.print("        .gui = .{{ .name = \"{s}\" }},\n", .{gui.name});
    }

    try w.writeAll("    },\n");

    if (cfg.plugins.len > 0) {
        try w.writeAll("    .plugins = .{\n");
        for (cfg.plugins) |plugin| {
            try w.print("        .{{ .name = \"{s}\", .repo = \"{s}\", .version = \"{s}\" }},\n", .{
                plugin.name, plugin.repo, plugin.version,
            });
        }
        try w.writeAll("    },\n");
    }

    try w.writeAll("}\n");

    const lock_path = try std.fs.path.join(allocator, &.{ project_dir, "labelle.lock" });
    defer allocator.free(lock_path);

    const file = try std.fs.cwd().createFile(lock_path, .{});
    defer file.close();
    try file.writeAll(buf.items);
}
