const std = @import("std");
const zspec = @import("zspec");
const generate = @import("generator");

test {
    zspec.runAll(@This());
}

// Engine codegen template (inlined for tests — normally loaded from engine's codegen/ directory)
const engine_template =
    \\/// Generated by labelle-cli — do not edit.
    \\const std = @import("std");
    \\const engine = @import("labelle-engine");
    \\const BackendGfx = @import("backend_gfx");
    \\const BackendInput = @import("backend_input");
    \\const BackendAudio = @import("backend_audio");
    \\const window = @import("backend_window");
    \\// Log sink (default: stderr). Override in project template to disable or customize.
    \\const LogSink = engine.core.StderrLogSink;
    \\{{#if ecs_mode_mock}}const EcsBackend = engine.MockEcsBackend(u32);
    \\{{#else}}const EcsAdapter = @import("ecs_backend");
    \\const EcsBackend = EcsAdapter;
    \\{{/if}}{{#if has_gui}}const GuiBackend = @import("gui_backend");
    \\{{#else}}const GuiBackend = engine.StubGui;
    \\{{/if}}{{hook_imports_block}}{{enum_imports_block}}{{jsonc_scene_block}}
    \\const gfx = @import("labelle-gfx");
    \\
    \\{{game_layers_block}}
    \\{{resource_registry_block}}const AllHookPayloads = engine.HookPayload(EcsBackend.Entity);
    \\
    \\{{game_hooks_block}}const Renderer = gfx.GfxRenderer(BackendGfx, GameLayers, EcsBackend.Entity);
    \\
    \\const AssembledGame = engine.GameConfig(
    \\    Renderer,
    \\    EcsBackend,
    \\    BackendInput,
    \\    BackendAudio,
    \\    GuiBackend,
    \\    *GameHooks,
    \\    LogSink,
    \\    Components,
    \\    DiscoveredGizmoCategories,
    \\);
    \\{{prefab_registry_block}}{{component_registry_block}}{{system_registry_block}}{{all_scripts_block}}const Scripts = engine.ScriptRegistry(AllScripts);
    \\
    \\{{#if has_context}}const GameContext = @import("scripts/context.zig").GameContext(EcsBackend);
    \\{{#else}}const GameContext = struct {};
    \\{{/if}}const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);
    \\
    \\{{view_registry_block}}{{gizmo_registry_block}}// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
    \\// The engine delegates to the renderer's renderGizmoDraws() method.
    \\{{lifecycle}}
;

// Minimal lifecycle templates for testing (mustache format — no shared sections)
const raylib_lifecycle =
    \\const screen_w: u32 = {{width}};
    \\const screen_h: u32 = {{height}};
    \\const screen_title = "{{title}}";
    \\const target_fps: u32 = {{fps}};
    \\pub fn main() !void {
    \\    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    \\    const allocator = gpa.allocator();
    \\{{hidden_setup}}    var hooks = GameHooks{};
    \\    var g = AssembledGame.init(allocator);
    \\    g.setHooks(&hooks);
    \\    g.renderer.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    \\{{setup_code}}
    \\    while (!window.windowShouldClose()) {
    \\        const dt: f32 = 0.016;
    \\{{tick_code}}        g.tick(dt);
    \\        g.render();
    \\{{gui_draw_code}}    }
    \\}
    \\
;

const sokol_lifecycle =
    \\var g: AssembledGame = undefined;
    \\var hooks: GameHooks = .{};
    \\var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    \\{{module_vars}}const screen_w: u32 = {{width}};
    \\const screen_h: u32 = {{height}};
    \\const screen_title = "{{title}}";
    \\const target_fps: u32 = {{fps}};
    \\export fn init() callconv(.c) void {
    \\{{hidden_setup}}    const allocator = gpa.allocator();
    \\    g = AssembledGame.init(allocator);
    \\    g.setHooks(&hooks);
    \\    g.renderer.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    \\{{init_code}}}
    \\export fn frame() callconv(.c) void {
    \\    const dt: f32 = 0.016;
    \\{{tick_code}}    g.tick(dt);
    \\    g.render();
    \\{{gui_draw_code}}}
    \\export fn cleanup() callconv(.c) void {
    \\{{cleanup_code}}    g.deinit();
    \\    _ = gpa.deinit();
    \\}
    \\
;

const empty_names: []const []const u8 = &.{};
const ScriptEntry = generate.script_scanner.ScriptScanner.ScriptEntry;
const empty_entries: []const ScriptEntry = &.{};

/// Helper: create global ScriptEntry values from a list of names (for testing).
/// Names are treated as filenames like "foo.zig" (no prefix, no state).
fn GlobalEntries(comptime names: []const []const u8) type {
    return struct {
        const entries = init: {
            var e: [names.len]ScriptEntry = undefined;
            for (names, 0..) |name, i| {
                e[i] = .{
                    .name = name,
                    .filename = name ++ ".zig",
                    .states = &.{},
                    .sort_order = null,
                    .subdir = null,
                    .rel_path = name ++ ".zig",
                };
            }
            break :init e;
        };
        const slice: []const ScriptEntry = &entries;
    };
}
fn globalEntries(comptime names: []const []const u8) []const ScriptEntry {
    return GlobalEntries(names).slice;
}

// Helper: create a ResolvedGui for testing (render_interface, no bridge)
fn testGuiRenderInterface(name: []const u8) generate.ResolvedGui {
    return .{
        .name = name,
        .rendering = .render_interface,
        .plugin_dir = "/fake/gui/plugin",
    };
}

// Helper: create a ResolvedGui for testing (raw_backend with lifecycle + bridge)
fn testGuiRawBackend(name: []const u8) generate.ResolvedGui {
    return .{
        .name = name,
        .rendering = .raw_backend,
        .lifecycle = .{ .init = true, .shutdown = true },
        .plugin_dir = "/fake/gui/plugin",
        .bridge_dir = "/fake/gui/bridge",
    };
}

// ── build.zig.zon generation ─────────────────────────────────────────

pub const BUILD_ZIG_ZON = struct {
    test "contains raylib dep for raylib backend" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_raylib") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_sokol") == null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_zig_ecs") == null);
    }

    test "contains zig_ecs dep when selected" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .zig_ecs,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_raylib") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_zig_ecs") != null);
    }

    test "contains sdl dep for sdl backend" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .sdl,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_sdl") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_raylib") == null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_sokol") == null);
    }

    test "contains bgfx dep for bgfx backend" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .bgfx,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_bgfx") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_raylib") == null);
    }

    test "contains wgpu dep for wgpu backend" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .wgpu,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_wgpu") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_raylib") == null);
    }

    test "uses config.version instead of hardcoded version" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .version = "1.2.3",
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, ".version = \"1.2.3\"") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, ".version = \"0.1.0\"") == null);
    }

    test "defaults to version 0.1.0" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, ".version = \"0.1.0\"") != null);
    }

    test "uses path deps by default" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, ".path =") != null);
    }
};

// ── build.zig generation ─────────────────────────────────────────────

pub const BUILD_ZIG = struct {
    test "links raylib artifact" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "linkLibrary") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "raylib") != null);
    }

    test "links sokol_clib artifact" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "linkLibrary") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "sokol_clib") != null);
    }

    test "wires sdl backend modules" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .sdl,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_sdl") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "backend_gfx") != null);
    }

    test "links bgfx and glfw artifacts" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .bgfx,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_bgfx") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "bgfx_artifact") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "glfw_artifact") != null);
    }

    test "links wgpu glfw artifact" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .wgpu,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_wgpu") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "glfw_artifact") != null);
    }

    test "deduplicates labelle-core across gfx and engine" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);

        // gfx and engine must use the project-level core, not their own resolved version
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(gfx_mod, \"labelle-core\", core_mod)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(engine_mod, \"labelle-core\", core_mod)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(engine_mod, \"labelle-gfx\", gfx_mod)") != null);
    }

    test "resolved_gui wires gui_backend" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
        });
        defer std.testing.allocator.free(build_zig);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "gui_mod") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_gui") != null);
    }

    test "resolved_gui raw_backend wires bridge artifact" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRawBackend("imgui"),
        });
        defer std.testing.allocator.free(build_zig);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "gui_bridge") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "gui_bridge_artifact") != null);
    }

    test "no gui omits gui_mod" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        });
        defer std.testing.allocator.free(build_zig);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "gui_mod") == null);
    }
};

// ── Plugin wiring ────────────────────────────────────────────────────

pub const PLUGINS = struct {
    test "no plugins excludes pathfinding/physics from build.zig.zon" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{},
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_pathfinding") == null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_physics") == null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_tasks") == null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_core") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_gfx") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "engine") != null);
    }

    test "no plugins excludes pathfinding/physics from build.zig" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{},
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_pathfinding") == null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_physics") == null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_tasks") == null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "pf_mod") == null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "physics_mod") == null);
    }

    test "plugins enabled includes pathfinding/physics in build.zig.zon" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{
                .{ .name = "pathfinding", .repo = "github.com/labelle-toolkit/labelle-pathfinding", .version = "0.1.0" },
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_pathfinding") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_physics") != null);
    }

    test "plugins enabled includes pathfinding/physics in build.zig" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{
                .{ .name = "pathfinding", .repo = "github.com/labelle-toolkit/labelle-pathfinding", .version = "0.1.0" },
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_pathfinding") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "labelle_physics") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "plugin_pathfinding_mod") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "plugin_physics_mod") != null);
    }

    test "plugins receive all engine subsystem imports" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .zig_ecs,
            .plugins = &.{
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        });
        defer std.testing.allocator.free(build_zig);

        // Core + gfx + engine (always injected)
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"labelle-core\", core_mod)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"labelle-gfx\", gfx_mod)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"labelle-engine\", engine_mod)") != null);

        // ECS backend (injected when ecs != mock)
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"ecs_backend\", ecs_mod)") != null);

        // Backend modules (always injected)
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"backend_gfx\", backend_gfx)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"backend_input\", backend_input)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"backend_audio\", backend_audio)") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"backend_window\", backend_window)") != null);
    }

    test "plugins with mock ecs omit ecs_backend import" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        });
        defer std.testing.allocator.free(build_zig);

        // Should NOT have ecs_backend when using mock
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(\"ecs_backend\"") == null);
        // But should still have core, gfx, engine
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"labelle-core\"") != null);
        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"labelle-engine\"") != null);
    }

    test "plugins receive gui_backend when gui is active" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
            .plugins = &.{
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(plugin_physics_mod, \"gui_backend\", gui_mod)") != null);
    }

    test "plugins omit gui_backend when no gui" {
        const build_zig = try generate.generateBuildZig(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{
                .{ .name = "physics", .repo = "github.com/labelle-toolkit/labelle-physics", .version = "0.1.0" },
            },
        });
        defer std.testing.allocator.free(build_zig);

        try std.testing.expect(std.mem.indexOf(u8, build_zig, "overrideImport(\"gui_backend\"") == null);
    }

    test "single plugin only includes that plugin" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .plugins = &.{
                .{ .name = "pathfinding", .repo = "github.com/labelle-toolkit/labelle-pathfinding", .version = "0.1.0" },
            },
        }, null, null, null);
        defer std.testing.allocator.free(zon);

        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_pathfinding") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_physics") == null);
    }
};

// ── main.zig generation ──────────────────────────────────────────────

pub const MAIN_ZIG = struct {
    test "uses MockEcsBackend for mock ecs" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "MockEcsBackend") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@import(\"ecs_backend\")") == null);
    }

    test "uses EcsAdapter for real ecs" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .zflecs,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "EcsAdapter") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "ecs_backend") != null);
    }

    test "contains window dimensions" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .title = "My Game",
            .width = 1024,
            .height = 768,
            .target_fps = 120,
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "1024") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "768") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "120") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "My Game") != null);
    }

    test "no gui uses StubGui" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "StubGui") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "gui_backend") == null);
    }

    test "resolved_gui wires gui_backend in main.zig" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "gui_backend") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "StubGui") == null);
    }

    test "resolved_gui with lifecycle generates init/shutdown" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRawBackend("imgui"),
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.init()") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.shutdown()") != null);
    }

    test "resolved_gui render_interface omits init/shutdown" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.init()") == null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.shutdown()") == null);
    }

    test "resolved_gui in zon includes labelle_gui dep" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
        }, null, null, null);
        defer std.testing.allocator.free(zon);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_gui") != null);
    }

    test "resolved_gui raw_backend in zon includes gui_bridge dep" {
        const zon = try generate.generateBuildZigZon(std.testing.allocator, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRawBackend("imgui"),
        }, null, null, null);
        defer std.testing.allocator.free(zon);
        try std.testing.expect(std.mem.indexOf(u8, zon, "labelle_gui") != null);
        try std.testing.expect(std.mem.indexOf(u8, zon, "gui_bridge") != null);
    }

    test "sets renderer screen height" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .height = 768,
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "setScreenHeight") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "768") != null);
    }

    test "sdl generates loop-based main" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sdl,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub fn main()") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "MockEcsBackend") != null);
    }
};

// ── Sokol backend ────────────────────────────────────────────────────

pub const SOKOL = struct {
    test "sets renderer screen height" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .height = 600,
            .backend = .sokol,
            .ecs = .mock,
        }, sokol_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "setScreenHeight") != null);
    }

    test "generates callback-style main" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
        }, sokol_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "export fn init() callconv(.c)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "export fn frame() callconv(.c)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "export fn cleanup() callconv(.c)") != null);
    }

    test "uses module-level runner var" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
        }, sokol_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "var runner: Runner = undefined;") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "runner = Runner.init(") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "runner.deinit()") != null);
    }

    test "initial_scene overrides default jsonc_scene_names[0]" {
        const jsonc_scenes = &[_][]const u8{ "intro", "main_menu", "gameplay" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
            .initial_scene = "main_menu",
        }, sokol_lifecycle, empty_entries, empty_names, jsonc_scenes, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "g.setScene(\"main_menu\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "g.setScene(\"intro\")") == null);
    }

    test "resolved_gui with lifecycle generates init in callback and shutdown in cleanup" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
            .resolved_gui = testGuiRawBackend("imgui"),
        }, sokol_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.init()") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GuiBackend.shutdown()") != null);
    }
};

// ── Embed scenes ────────────────────────────────────────────────────

pub const EMBED_SCENES = struct {
    test "scenes are always embedded via @embedFile" {
        const jsonc_scenes = &[_][]const u8{ "intro", "gameplay" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, jsonc_scenes, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"scenes/intro.jsonc\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"scenes/gameplay.jsonc\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "loadSceneFromSource") != null);
        // No file-based loadScene
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "loadScene(game") == null);
    }
};

// ── Scripts ──────────────────────────────────────────────────────────

pub const SCRIPTS = struct {
    test "generates AllScripts struct for global scripts" {
        const entries = globalEntries(&.{ "movement", "spawn", "gui" });
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const AllScripts = struct {") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const movement = @import(\"scripts/movement.zig\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const spawn = @import(\"scripts/spawn.zig\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const gui = @import(\"scripts/gui.zig\")") != null);
    }

    test "generates state-scoped wrapper for state-bound scripts" {
        const playing_states: []const []const u8 = &.{"playing"};
        const entries: []const ScriptEntry = &.{
            .{ .name = "movement", .filename = "movement.zig", .states = &.{}, .sort_order = null, .subdir = null, .rel_path = "movement.zig" },
            .{ .name = "pathfinder", .filename = "01_pathfinder.zig", .states = playing_states, .sort_order = 1, .subdir = "playing", .rel_path = "playing/01_pathfinder.zig" },
        };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // Global script: direct import, no wrapper
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const movement = @import(\"scripts/movement.zig\")") != null);
        // State-scoped script: wrapper with game_states (identifier derived from rel_path)
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const playing_01_pathfinder = struct {") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "_inner = @import(\"scripts/playing/01_pathfinder.zig\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const game_states = .{") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "\"playing\",") != null);
    }

    test "generates multi-state wrapper for playing+paused scripts" {
        const both_states: []const []const u8 = &.{ "playing", "paused" };
        const entries: []const ScriptEntry = &.{
            .{ .name = "camera", .filename = "camera.zig", .states = both_states, .sort_order = null, .subdir = "playing+paused", .rel_path = "playing+paused/camera.zig" },
        };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const playing_paused_camera = struct {") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "\"playing\",") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "\"paused\",") != null);
    }

    test "uses ScriptRunner for dispatch" {
        const entries = globalEntries(&.{ "movement", "spawn" });
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "Runner.init(allocator, &g.active_world.ecs_backend)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "runner.setup(&g)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "runner.tick(&g, scaled_dt)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "runner.deinit()") != null);
    }

    test "detects context.zig for GameContext" {
        const entries = globalEntries(&.{ "context", "movement" });
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const GameContext = @import(\"scripts/context.zig\").GameContext(EcsBackend)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const context =") == null);
    }

    test "uses empty struct when no context.zig" {
        const entries = globalEntries(&.{"movement"});
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const GameContext = struct {}") != null);
    }
};

// ── Prefabs & Scenes ─────────────────────────────────────────────────

pub const PREFABS_AND_SCENES = struct {
    test "embeds prefabs via addEmbeddedPrefab" {
        const prefabs = &[_][]const u8{ "enemy", "player" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, prefabs, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // Prefabs are embedded at runtime, not compiled via PrefabRegistry
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "addEmbeddedPrefab") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"prefabs/player.jsonc\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"prefabs/enemy.jsonc\")") != null);
        // Empty comptime PrefabRegistry
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "PrefabRegistry(.{})") != null);
    }

};

// ── Views ────────────────────────────────────────────────────────────

pub const VIEWS = struct {
    test "generates ViewRegistry from scanned views" {
        const views = &[_][]const u8{ "hud", "inventory" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, views, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const Views = engine.ViewRegistry(.{") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".hud = @import(\"views/hud.zon\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".inventory = @import(\"views/inventory.zon\")") != null);
    }

    test "auto-renders views in GUI section" {
        const views = &[_][]const u8{"hud"};
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resolved_gui = testGuiRenderInterface("clay"),
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, views, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "g.guiBegin()") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "g.renderAllViews(Views)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "g.guiEnd()") != null);
    }

    test "uses EmptyViewRegistry when no views" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const Views = engine.EmptyViewRegistry") != null);
    }
};

// ── Layers & Resources ───────────────────────────────────────────────

pub const LAYERS = struct {
    test "generates GameLayers from project config" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .layers = &.{
                .{ .name = "bg", .order = 0, .space = .screen },
                .{ .name = "world", .order = 1, .space = .world },
                .{ .name = "hud", .order = 2, .space = .screen },
            },
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "const GameLayers = enum(u8)") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "bg,") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "world,") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "hud,") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".bg => .{ .order = 0, .space = .screen }") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".world => .{ .order = 1, .space = .world }") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "GfxRenderer(BackendGfx, GameLayers,") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "config.GameLayers") == null);
    }
};

pub const RESOURCES = struct {
    test "generates embedded atlas loading from resource config" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .resources = &.{
                .{ .name = "characters", .json = "assets/characters.json", .texture = "assets/characters.png" },
                .{ .name = "tiles", .json = "assets/tiles.json", .texture = "assets/tiles.png" },
            },
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // Resources are embedded via @embedFile + loadAtlasFromMemory
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "loadAtlasFromMemory(\"characters\"") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"assets/characters.json\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"assets/characters.png\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "loadAtlasFromMemory(\"tiles\"") != null);
        // No comptime ResourceRegistry
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "ResourceRegistry") == null);
    }

    test "omits atlas loading when no resources" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "loadAtlasFromMemory") == null);
    }
};

// ── Hidden window flag ───────────────────────────────────────────────

pub const HIDDEN_WINDOW = struct {
    test "hidden=true generates window hidden flag in raylib" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .hidden = true,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "window.setConfigFlags(.{ .window_hidden = true })") != null);
    }

    test "hidden=false does not generate window hidden flag" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
            .hidden = false,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "window_hidden") == null);
    }

    test "hidden=true generates window hidden flag in sokol" {
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .sokol,
            .ecs = .mock,
            .hidden = true,
        }, sokol_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, "window.setConfigFlags(.{ .window_hidden = true })") != null);
    }
};

// ── Subfolder support ────────────────────────────────────────────────

pub const SUBFOLDERS = struct {
    test "prefab names with slashes use slash paths in embedFile" {
        const prefabs = &[_][]const u8{ "enemies/goblin", "enemies/orc", "player" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, prefabs, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // Subfolder prefabs embedded with slash paths
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"prefabs/enemies/goblin.jsonc\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"prefabs/enemies/orc.jsonc\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@embedFile(\"prefabs/player.jsonc\")") != null);
    }

    test "scripts in organizational subdirs use path-based identifiers" {
        const playing_states: []const []const u8 = &.{"playing"};
        const entries: []const ScriptEntry = &.{
            .{ .name = "movement", .filename = "movement.zig", .states = playing_states, .sort_order = null, .subdir = "playing", .rel_path = "playing/systems/movement.zig" },
            .{ .name = "combat", .filename = "combat.zig", .states = playing_states, .sort_order = null, .subdir = "playing", .rel_path = "playing/systems/combat.zig" },
            .{ .name = "camera_control", .filename = "camera_control.zig", .states = &.{}, .sort_order = null, .subdir = null, .rel_path = "camera_control.zig" },
        };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // State-scoped scripts: identifier derived from rel_path, import uses full path
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const playing_systems_movement = struct {") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@import(\"scripts/playing/systems/movement.zig\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const playing_systems_combat = struct {") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "@import(\"scripts/playing/systems/combat.zig\")") != null);
        // Global script: direct import
        try std.testing.expect(std.mem.indexOf(u8, main_zig, "pub const camera_control = @import(\"scripts/camera_control.zig\")") != null);
    }

    test "component names with slashes use underscore PascalCase identifiers" {
        const components = &[_][]const u8{ "physics/rigid_body", "health" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, components, empty_names, empty_names, empty_names, empty_names, empty_names);
        defer std.testing.allocator.free(main_zig);

        // Subfolder component: path with slash, PascalCase from flattened ident
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".PhysicsRigidBody = @import(\"components/physics/rigid_body.zig\").PhysicsRigidBody") != null);
        // Top-level component unchanged
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".Health = @import(\"components/health.zig\").Health") != null);
    }

    test "gizmo names with slashes use underscore identifiers" {
        const gizmos = &[_][]const u8{ "debug/collision", "editor/grid" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, gizmos);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".debug_collision = @import(\"gizmos/debug/collision.zon\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".editor_grid = @import(\"gizmos/editor/grid.zon\")") != null);
    }

    test "view names with slashes use underscore identifiers" {
        const views = &[_][]const u8{ "panels/inventory", "hud" };
        const main_zig = try generate.generateMainZigFromTemplate(std.testing.allocator, engine_template, .{
            .name = "test-game",
            .backend = .raylib,
            .ecs = .mock,
        }, raylib_lifecycle, empty_entries, empty_names, empty_names, empty_names, empty_names, empty_names, empty_names, views, empty_names);
        defer std.testing.allocator.free(main_zig);

        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".panels_inventory = @import(\"views/panels/inventory.zon\")") != null);
        try std.testing.expect(std.mem.indexOf(u8, main_zig, ".hud = @import(\"views/hud.zon\")") != null);
    }
};
