/// Generated by labelle-cli — do not edit.
const std = @import("std");
const engine = @import("labelle-engine");
const BackendGfx = @import("backend_gfx");
const BackendInput = @import("backend_input");
const BackendAudio = @import("backend_audio");
const window = @import("backend_window");
// Log sink (default: stderr). Override in project template to disable or customize.
const LogSink = engine.core.StderrLogSink;
const EcsAdapter = @import("ecs_backend");
const EcsBackend = EcsAdapter;
const GuiBackend = engine.StubGui;

// --- Scene data ---
const main_scene = @import("scenes/main.zon");

const gfx = @import("labelle-gfx");

const GameLayers = enum(u8) {
    background,
    world,
    ui,

    pub fn config(self: GameLayers) gfx.LayerConfig {
        return switch (self) {
            .background => .{ .order = 0, .space = .screen },
            .world => .{ .order = 1, .space = .world },
            .ui => .{ .order = 2, .space = .screen },
        };
    }
};

const GameHooks = struct {};

const Renderer = gfx.GfxRenderer(BackendGfx, GameLayers, EcsBackend.Entity);

const AssembledGame = engine.GameConfig(
    Renderer,
    EcsBackend,
    BackendInput,
    BackendAudio,
    GuiBackend,
    *GameHooks,
    LogSink,
);
const Prefabs = engine.PrefabRegistry(.{});

const Components = engine.ComponentRegistry(.{
    .Carrier = @import("components/carrier.zig").Carrier,
    .ManualCarrier = @import("components/manual_carrier.zig").ManualCarrier,
    .PickupItem = @import("components/pickup_item.zig").PickupItem,
});

const AllScripts = struct {
    pub const carry_demo = @import("scripts/carry_demo.zig");
    pub const manual_carry = @import("scripts/manual_carry.zig");
};

const Scripts = engine.ScriptRegistry(AllScripts);

const GameContext = struct {};
const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);

const Views = engine.EmptyViewRegistry;

// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
// The engine delegates to the renderer's renderGizmoDraws() method.
const screen_w: u32 = 800;
const screen_h: u32 = 400;
const screen_title = "Carry Test — Parent/Child Position";
const target_fps: u32 = 60;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    window.initWindow(screen_w, screen_h, screen_title);
    defer window.closeWindow();
    window.setTargetFPS(target_fps);

    var hooks = GameHooks{};
    var g = AssembledGame.init(allocator);
    defer g.deinit();

    g.setHooks(&hooks);

    g.renderer.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    g.renderer.getCamera().setPosition(0, @as(f32, @floatFromInt(screen_h)));

    var runner = Runner.init(allocator, &g.ecs_backend);
    defer runner.deinit();

    const Loader = engine.SceneLoader(AssembledGame, Prefabs, Components, Scripts);
    g.registerSceneSimple("main", Loader.sceneLoaderFn(main_scene));
    try g.setScene("main");

    runner.setup(&g);

    while (!window.windowShouldClose()) {
        const dt: f32 = 0.016;
        runner.tick(&g, dt);
        g.tick(dt);

        window.beginDrawing();
        window.clearBackground(30, 30, 35, 255);
        g.render();
        g.renderGizmos();
        window.drawText(screen_title, 10, 10, 20, 180, 180, 180, 255);
        window.endDrawing();
    }
}
