//! Android launcher-icon staging (labelle-cli#340).
//!
//! `project.labelle` has carried an `app_icon` field for a while, but
//! nothing consumed it — every packaged APK shipped with the stock
//! Android robot. This module closes that gap: it resolves which PNG is
//! the app icon, downscales it to the five launcher densities, and
//! writes them into the APK staging tree as
//! `res/mipmap-<density>/ic_launcher.png` for aapt to compile.
//!
//! ## Precedence (mirrors labelle-assembler `src/app_icon.zig`)
//!
//! The assembler OWNS the default icon. On every `generate` it writes
//! its embedded branded default to `<target_dir>/default_icon.png` — at
//! the target-dir ROOT, not under `assets/`, because `assets/` in the
//! target is a symlink back into the source project. When a project sets
//! a non-empty `app_icon` the assembler instead deletes any stale
//! `default_icon.png`, so the two cases never overlap on disk.
//!
//! This module must agree with that exactly:
//!   * `app_icon` non-null and non-empty  → `<project_root>/<app_icon>`
//!   * `app_icon` null or `""`            → `<target_dir>/default_icon.png`
//!
//! `""` is treated as unset, same as the assembler.
//!
//! ## Failure policy
//!
//! A project that names an icon and gets the stock robot anyway is the
//! exact bug this module exists to kill, so a *custom* icon that is
//! missing or undecodable is a hard error naming the path — never a
//! silent fall back to the default.
//!
//! An *absent* `default_icon.png` is different: it just means the
//! project was generated by an assembler older than the one that emits
//! it. That degrades to "no launcher icon staged" (and the manifest
//! omits `android:icon`, see `package.zig`) rather than breaking every
//! build against an older assembler. A default that exists but does not
//! decode is a real error like any other.

const std = @import("std");
const config = @import("../config.zig");

const c = @cImport({
    @cInclude("stb_image.h");
    @cInclude("stb_image_write.h");
});

/// Filename the assembler writes its bundled default icon to, relative
/// to the generated target dir. Contract with labelle-assembler
/// `src/app_icon.zig` — changing it here alone silently disables the
/// default icon.
pub const default_icon_name = "default_icon.png";

/// Resource subdirectory inside the APK staging tree. Handed to aapt as
/// `-S <staging>/res`.
pub const res_subdir = "res";

/// The manifest reference the staged mipmaps satisfy.
pub const icon_resource_ref = "@mipmap/ic_launcher";

/// One Android launcher density bucket. `dir` is the resource
/// directory name, `size` the square edge length in pixels.
pub const Density = struct {
    dir: []const u8,
    size: u32,
};

/// The launcher densities we emit. These are the standard Android
/// buckets; a device picks the closest one at install time, so shipping
/// all five means no scaling artefacts on any screen.
pub const densities = [_]Density{
    .{ .dir = "mipmap-mdpi", .size = 48 },
    .{ .dir = "mipmap-hdpi", .size = 72 },
    .{ .dir = "mipmap-xhdpi", .size = 96 },
    .{ .dir = "mipmap-xxhdpi", .size = 144 },
    .{ .dir = "mipmap-xxxhdpi", .size = 192 },
};

/// Which of the two icon sources a resolved path came from. The
/// distinction drives the failure policy: a missing `.custom` is fatal,
/// a missing `.default` just means "older assembler, no icon".
pub const Source = enum { custom, default };

/// A resolved icon path plus where it came from. `path` is owned by the
/// caller's allocator.
pub const Resolved = struct {
    path: []u8,
    source: Source,

    pub fn deinit(self: Resolved, allocator: std.mem.Allocator) void {
        allocator.free(self.path);
    }
};

/// Resolve the effective launcher-icon path. This is the ONE place the
/// custom-vs-default precedence lives; every other code path goes
/// through it so the CLI and the assembler cannot drift apart.
///
/// See the module doc comment for the precedence rules.
pub fn resolve(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    target_dir: []const u8,
    app_icon: ?[]const u8,
) !Resolved {
    if (app_icon) |rel| {
        if (rel.len > 0) return .{
            .path = try std.fs.path.join(allocator, &.{ project_dir, rel }),
            .source = .custom,
        };
    }
    return .{
        .path = try std.fs.path.join(allocator, &.{ target_dir, default_icon_name }),
        .source = .default,
    };
}

/// Generate `res/mipmap-*/ic_launcher.png` under `staging_dir`.
///
/// Returns `true` when the mipmaps were written (so the caller passes
/// `-S` to aapt and puts `android:icon` in the manifest), `false` when
/// there was no icon to stage at all — which happens only for a
/// `default_icon.png` that the generating assembler never wrote.
///
/// Errors (all loud, all naming the offending path):
///   * `error.LauncherIconNotFound`     — `app_icon` points at nothing
///   * `error.LauncherIconDecodeFailed` — the file is not a decodable PNG
pub fn stage(
    allocator: std.mem.Allocator,
    staging_dir: []const u8,
    project_dir: []const u8,
    target_dir: []const u8,
    app_icon: ?[]const u8,
) !bool {
    const resolved = try resolve(allocator, project_dir, target_dir, app_icon);
    defer resolved.deinit(allocator);

    const io = config.globalIo();
    const bytes = std.Io.Dir.cwd().readFileAlloc(io, resolved.path, allocator, .unlimited) catch |err| switch (err) {
        error.FileNotFound => switch (resolved.source) {
            .custom => {
                std.debug.print(
                    \\labelle: app_icon not found at {s}
                    \\  `.app_icon` in project.labelle is resolved relative to the project root.
                    \\  Fix the path or remove `.app_icon` to use the bundled default icon.
                    \\
                , .{resolved.path});
                return error.LauncherIconNotFound;
            },
            // No assembler-provided default: this project was generated
            // by an assembler that predates the bundled icon. Ship the
            // APK without a custom launcher icon rather than failing.
            .default => {
                std.debug.print(
                    "labelle: no {s} in {s} — packaging without a launcher icon (upgrade labelle-assembler to get the bundled default)\n",
                    .{ default_icon_name, target_dir },
                );
                return false;
            },
        },
        else => {
            std.debug.print("labelle: could not read app icon {s}: {s}\n", .{ resolved.path, @errorName(err) });
            return err;
        },
    };
    defer allocator.free(bytes);

    const img = decodePng(bytes) catch {
        std.debug.print(
            \\labelle: app icon {s} is not a decodable PNG
            \\  launcher icons must be PNG; a square source of at least {d}x{d} gives the best result.
            \\
        , .{ resolved.path, densities[densities.len - 1].size, densities[densities.len - 1].size });
        return error.LauncherIconDecodeFailed;
    };
    defer img.free();

    const res_dir = try std.fs.path.join(allocator, &.{ staging_dir, res_subdir });
    defer allocator.free(res_dir);

    for (densities) |d| {
        const dir = try std.fs.path.join(allocator, &.{ res_dir, d.dir });
        defer allocator.free(dir);
        try std.Io.Dir.cwd().createDirPath(io, dir);

        const scaled = try resampleBox(allocator, img.pixels, img.width, img.height, d.size, d.size);
        defer allocator.free(scaled);

        const png = try encodePng(allocator, scaled, d.size, d.size);
        defer allocator.free(png);

        const out = try std.fs.path.join(allocator, &.{ dir, "ic_launcher.png" });
        defer allocator.free(out);
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out, .data = png });
    }

    std.debug.print("labelle: launcher icon from {s}\n", .{resolved.path});
    return true;
}

/// A decoded RGBA image. `pixels` is stb-owned memory, not the Zig
/// allocator's — release it with `free()`.
const DecodedImage = struct {
    pixels: []const u8,
    width: usize,
    height: usize,

    fn free(self: DecodedImage) void {
        c.stbi_image_free(@constCast(@ptrCast(self.pixels.ptr)));
    }
};

/// Decode PNG bytes to tightly-packed RGBA8. The bundled default is
/// opaque RGB (colour-type 2); forcing 4 channels means one uniform
/// resample path regardless of what a project supplies.
fn decodePng(bytes: []const u8) !DecodedImage {
    var w: c_int = 0;
    var h: c_int = 0;
    var ch: c_int = 0;
    const raw = c.stbi_load_from_memory(@ptrCast(bytes.ptr), @intCast(bytes.len), &w, &h, &ch, 4);
    if (raw == null) return error.DecodeFailed;
    errdefer c.stbi_image_free(raw);
    if (w <= 0 or h <= 0) return error.DecodeFailed;

    // Checked multiplication: stb_image permits up to 2^24 per axis, so
    // `w * h * 4` can overflow `usize` on 32-bit hosts (mirrors the
    // same guard in `cli/bake.zig`).
    const wh = std.math.mul(usize, @as(usize, @intCast(w)), @as(usize, @intCast(h))) catch return error.DecodeFailed;
    const len = std.math.mul(usize, wh, 4) catch return error.DecodeFailed;

    return .{
        .pixels = @as([*]const u8, @ptrCast(raw))[0..len],
        .width = @intCast(w),
        .height = @intCast(h),
    };
}

/// Area-average ("box") resample of a tightly-packed RGBA8 image.
///
/// Nearest-neighbour is not good enough here: the launcher sizes are
/// non-integer ratios of a 512px source (512→192 is 2.666…, 512→72 is
/// 7.111…), so point sampling drops most of the source pixels and
/// aliases badly on detailed art. Instead every destination pixel
/// averages its full source-pixel footprint, with fractional weights on
/// the partially-covered edge pixels.
///
/// Colour is averaged in premultiplied-alpha space (each sample's RGB is
/// weighted by its own alpha) so transparent source pixels can't bleed
/// their colour into the edges of a soft-alpha icon. Fully opaque input
/// — like the bundled default — reduces to a plain weighted mean.
///
/// Works for upscaling too (a sub-pixel footprint degenerates to a
/// 1-4 pixel blend), though in practice this only ever downscales.
/// Caller owns the returned buffer.
pub fn resampleBox(
    allocator: std.mem.Allocator,
    src: []const u8,
    src_w: usize,
    src_h: usize,
    dst_w: usize,
    dst_h: usize,
) ![]u8 {
    if (src_w == 0 or src_h == 0 or dst_w == 0 or dst_h == 0) return error.InvalidDimensions;
    const src_len = try std.math.mul(usize, try std.math.mul(usize, src_w, src_h), 4);
    if (src.len < src_len) return error.InvalidDimensions;

    const dst_len = try std.math.mul(usize, try std.math.mul(usize, dst_w, dst_h), 4);
    const dst = try allocator.alloc(u8, dst_len);
    errdefer allocator.free(dst);

    const ratio_x = @as(f64, @floatFromInt(src_w)) / @as(f64, @floatFromInt(dst_w));
    const ratio_y = @as(f64, @floatFromInt(src_h)) / @as(f64, @floatFromInt(dst_h));

    var dy: usize = 0;
    while (dy < dst_h) : (dy += 1) {
        const y0 = @as(f64, @floatFromInt(dy)) * ratio_y;
        const y1 = @min(y0 + ratio_y, @as(f64, @floatFromInt(src_h)));
        const ys = @min(src_h - 1, @as(usize, @intFromFloat(@floor(y0))));
        const ye = @min(src_h, @max(ys + 1, @as(usize, @intFromFloat(@ceil(y1)))));

        var dx: usize = 0;
        while (dx < dst_w) : (dx += 1) {
            const x0 = @as(f64, @floatFromInt(dx)) * ratio_x;
            const x1 = @min(x0 + ratio_x, @as(f64, @floatFromInt(src_w)));
            const xs = @min(src_w - 1, @as(usize, @intFromFloat(@floor(x0))));
            const xe = @min(src_w, @max(xs + 1, @as(usize, @intFromFloat(@ceil(x1)))));

            var weight_sum: f64 = 0;
            var acc_a: f64 = 0;
            var acc_r: f64 = 0;
            var acc_g: f64 = 0;
            var acc_b: f64 = 0;

            var sy = ys;
            while (sy < ye) : (sy += 1) {
                const wy = @min(y1, @as(f64, @floatFromInt(sy + 1))) - @max(y0, @as(f64, @floatFromInt(sy)));
                if (wy <= 0) continue;
                var sx = xs;
                while (sx < xe) : (sx += 1) {
                    const wx = @min(x1, @as(f64, @floatFromInt(sx + 1))) - @max(x0, @as(f64, @floatFromInt(sx)));
                    if (wx <= 0) continue;
                    const w = wx * wy;
                    const p = (sy * src_w + sx) * 4;
                    const a = @as(f64, @floatFromInt(src[p + 3]));
                    weight_sum += w;
                    acc_a += a * w;
                    acc_r += @as(f64, @floatFromInt(src[p + 0])) * a * w;
                    acc_g += @as(f64, @floatFromInt(src[p + 1])) * a * w;
                    acc_b += @as(f64, @floatFromInt(src[p + 2])) * a * w;
                }
            }

            const q = (dy * dst_w + dx) * 4;
            if (weight_sum <= 0) {
                // Unreachable in practice (the ys/ye clamps guarantee at
                // least one positive-weight sample); stay total rather
                // than divide by zero.
                @memset(dst[q .. q + 4], 0);
                continue;
            }
            // Un-premultiply: dividing the alpha-weighted colour sums by
            // the alpha sum (not the weight sum) recovers the mean
            // colour of the *visible* part of the footprint.
            if (acc_a > 0) {
                dst[q + 0] = quantize(acc_r / acc_a);
                dst[q + 1] = quantize(acc_g / acc_a);
                dst[q + 2] = quantize(acc_b / acc_a);
            } else {
                dst[q + 0] = 0;
                dst[q + 1] = 0;
                dst[q + 2] = 0;
            }
            dst[q + 3] = quantize(acc_a / weight_sum);
        }
    }

    return dst;
}

/// Round a channel accumulator to a u8, clamping out float slop.
fn quantize(v: f64) u8 {
    return @intFromFloat(@round(std.math.clamp(v, 0, 255)));
}

/// Collects stb_image_write's output chunks. `stbi_write_png_to_func`
/// is the only encode entry point available: the vendored
/// implementation is compiled with `STBI_WRITE_NO_STDIO`.
const PngSink = struct {
    list: std.ArrayList(u8),
    allocator: std.mem.Allocator,
    failed: bool = false,
};

fn pngWrite(ctx: ?*anyopaque, data: ?*anyopaque, size: c_int) callconv(.c) void {
    const sink: *PngSink = @ptrCast(@alignCast(ctx.?));
    if (sink.failed or size <= 0) return;
    const bytes: [*]const u8 = @ptrCast(data.?);
    sink.list.appendSlice(sink.allocator, bytes[0..@intCast(size)]) catch {
        sink.failed = true;
    };
}

/// Encode tightly-packed RGBA8 pixels to PNG bytes. Caller owns them.
pub fn encodePng(allocator: std.mem.Allocator, px: []const u8, w: usize, h: usize) ![]u8 {
    const need = try std.math.mul(usize, try std.math.mul(usize, w, h), 4);
    if (px.len < need) return error.InvalidDimensions;

    var sink: PngSink = .{ .list = .empty, .allocator = allocator };
    errdefer sink.list.deinit(allocator);
    const ok = c.stbi_write_png_to_func(
        pngWrite,
        &sink,
        @intCast(w),
        @intCast(h),
        4,
        px.ptr,
        @intCast(w * 4),
    );
    if (ok == 0 or sink.failed) return error.EncodeFailed;
    return sink.list.toOwnedSlice(allocator);
}

// ── Tests ──────────────────────────────────────────────────────────

const testing = std.testing;

/// Build a `w`x`h` RGBA test image whose pixels vary in both axes, so a
/// resample that silently point-samples produces different bytes than
/// one that averages.
fn gradientRgba(allocator: std.mem.Allocator, w: usize, h: usize) ![]u8 {
    const px = try allocator.alloc(u8, w * h * 4);
    for (0..h) |y| {
        for (0..w) |x| {
            const p = (y * w + x) * 4;
            px[p + 0] = @intCast((x * 255) / (w - 1));
            px[p + 1] = @intCast((y * 255) / (h - 1));
            px[p + 2] = 128;
            px[p + 3] = 255;
        }
    }
    return px;
}

test "resolve prefers a non-empty app_icon, joined against the project root" {
    const a = testing.allocator;
    const r = try resolve(a, "/proj", "/proj/.labelle/bgfx_android", "art/icon.png");
    defer r.deinit(a);
    try testing.expectEqual(Source.custom, r.source);
    try testing.expectEqualStrings("/proj/art/icon.png", r.path);
}

test "resolve falls back to the assembler default when app_icon is null" {
    const a = testing.allocator;
    const r = try resolve(a, "/proj", "/proj/.labelle/bgfx_android", null);
    defer r.deinit(a);
    try testing.expectEqual(Source.default, r.source);
    try testing.expectEqualStrings("/proj/.labelle/bgfx_android/default_icon.png", r.path);
}

test "resolve treats an empty app_icon as unset (matches the assembler)" {
    const a = testing.allocator;
    const r = try resolve(a, "/proj", "/tgt", "");
    defer r.deinit(a);
    try testing.expectEqual(Source.default, r.source);
    try testing.expectEqualStrings("/tgt/default_icon.png", r.path);
}

test "resampleBox averages the whole footprint rather than point sampling" {
    const a = testing.allocator;
    // 2x2 with four distinct opaque colours; one destination pixel must
    // be their mean. Nearest-neighbour would return a single corner.
    const src = [_]u8{
        0,   0,   0,   255, 100, 100, 100, 255,
        200, 200, 200, 255, 255, 255, 255, 255,
    };
    const out = try resampleBox(a, &src, 2, 2, 1, 1);
    defer a.free(out);
    try testing.expectEqual(@as(usize, 4), out.len);
    // (0 + 100 + 200 + 255) / 4 = 138.75 → 139
    try testing.expectEqual(@as(u8, 139), out[0]);
    try testing.expectEqual(@as(u8, 139), out[1]);
    try testing.expectEqual(@as(u8, 139), out[2]);
    try testing.expectEqual(@as(u8, 255), out[3]);
}

test "resampleBox weights partially covered source pixels" {
    const a = testing.allocator;
    // 3 source pixels → 2 destination pixels: each destination covers
    // 1.5 source pixels, so the middle one is split evenly.
    const src = [_]u8{ 0, 0, 0, 255, 100, 100, 100, 255, 200, 200, 200, 255 };
    const out = try resampleBox(a, &src, 3, 1, 2, 1);
    defer a.free(out);
    // dst0 = (0*1 + 100*0.5) / 1.5 = 33.33 → 33
    try testing.expectEqual(@as(u8, 33), out[0]);
    // dst1 = (100*0.5 + 200*1) / 1.5 = 166.67 → 167
    try testing.expectEqual(@as(u8, 167), out[4]);
}

test "resampleBox ignores the colour of fully transparent source pixels" {
    const a = testing.allocator;
    // A transparent magenta pixel next to an opaque black one: naive
    // (non-premultiplied) averaging would tint the result magenta.
    const src = [_]u8{ 0, 0, 0, 255, 255, 0, 255, 0 };
    const out = try resampleBox(a, &src, 2, 1, 1, 1);
    defer a.free(out);
    try testing.expectEqual(@as(u8, 0), out[0]);
    try testing.expectEqual(@as(u8, 0), out[1]);
    try testing.expectEqual(@as(u8, 0), out[2]);
    try testing.expectEqual(@as(u8, 128), out[3]); // 255/2 = 127.5 → 128
}

test "resampleBox rejects zero and undersized inputs" {
    const a = testing.allocator;
    const src = [_]u8{ 1, 2, 3, 4 };
    try testing.expectError(error.InvalidDimensions, resampleBox(a, &src, 0, 1, 1, 1));
    try testing.expectError(error.InvalidDimensions, resampleBox(a, &src, 1, 1, 1, 0));
    // Claims 4x4 but only one pixel of storage.
    try testing.expectError(error.InvalidDimensions, resampleBox(a, &src, 4, 4, 2, 2));
}

test "encodePng round-trips through the decoder at every launcher density" {
    const a = testing.allocator;
    const src = try gradientRgba(a, 512, 512);
    defer a.free(src);

    for (densities) |d| {
        const scaled = try resampleBox(a, src, 512, 512, d.size, d.size);
        defer a.free(scaled);
        try testing.expectEqual(@as(usize, d.size) * d.size * 4, scaled.len);

        const png = try encodePng(a, scaled, d.size, d.size);
        defer a.free(png);

        // Byte-valid PNG: correct 8-byte signature...
        try testing.expect(png.len > 8);
        try testing.expectEqualSlices(u8, &.{ 0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n' }, png[0..8]);
        // ...and it decodes back at the requested dimensions.
        const img = try decodePng(png);
        defer img.free();
        try testing.expectEqual(@as(usize, d.size), img.width);
        try testing.expectEqual(@as(usize, d.size), img.height);
        try testing.expectEqualSlices(u8, scaled, img.pixels);
    }
}

test "stage writes one ic_launcher.png per density and reports success" {
    const a = testing.allocator;
    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();

    const work = ".zig-cache/launcher-icon-stage";
    cwd.deleteTree(io, work) catch {};
    defer cwd.deleteTree(io, work) catch {};
    const project = try std.fs.path.join(a, &.{ work, "proj" });
    defer a.free(project);
    const staging = try std.fs.path.join(a, &.{ work, "staging" });
    defer a.free(staging);
    try cwd.createDirPath(io, project);
    try cwd.createDirPath(io, staging);

    // A 256x256 custom icon at <project>/art/icon.png.
    const art = try std.fs.path.join(a, &.{ project, "art" });
    defer a.free(art);
    try cwd.createDirPath(io, art);
    const src = try gradientRgba(a, 256, 256);
    defer a.free(src);
    const png = try encodePng(a, src, 256, 256);
    defer a.free(png);
    const icon_path = try std.fs.path.join(a, &.{ art, "icon.png" });
    defer a.free(icon_path);
    try cwd.writeFile(io, .{ .sub_path = icon_path, .data = png });

    try testing.expect(try stage(a, staging, project, work, "art/icon.png"));

    for (densities) |d| {
        const out = try std.fs.path.join(a, &.{ staging, res_subdir, d.dir, "ic_launcher.png" });
        defer a.free(out);
        const bytes = try cwd.readFileAlloc(io, out, a, .unlimited);
        defer a.free(bytes);
        const img = try decodePng(bytes);
        defer img.free();
        try testing.expectEqual(@as(usize, d.size), img.width);
        try testing.expectEqual(@as(usize, d.size), img.height);
    }
}

test "stage picks up the assembler default when the project sets no app_icon" {
    const a = testing.allocator;
    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();

    const work = ".zig-cache/launcher-icon-default";
    cwd.deleteTree(io, work) catch {};
    defer cwd.deleteTree(io, work) catch {};
    const target = try std.fs.path.join(a, &.{ work, "target" });
    defer a.free(target);
    const staging = try std.fs.path.join(a, &.{ work, "staging" });
    defer a.free(staging);
    try cwd.createDirPath(io, target);
    try cwd.createDirPath(io, staging);

    const src = try gradientRgba(a, 64, 64);
    defer a.free(src);
    const png = try encodePng(a, src, 64, 64);
    defer a.free(png);
    const default_path = try std.fs.path.join(a, &.{ target, default_icon_name });
    defer a.free(default_path);
    try cwd.writeFile(io, .{ .sub_path = default_path, .data = png });

    try testing.expect(try stage(a, staging, work, target, null));

    const out = try std.fs.path.join(a, &.{ staging, res_subdir, "mipmap-mdpi", "ic_launcher.png" });
    defer a.free(out);
    try cwd.access(io, out, .{});
}

test "stage fails loudly when app_icon names a file that does not exist" {
    const a = testing.allocator;
    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();

    const work = ".zig-cache/launcher-icon-missing";
    cwd.deleteTree(io, work) catch {};
    defer cwd.deleteTree(io, work) catch {};
    try cwd.createDirPath(io, work);

    // Never silently falls back — even when a usable default sits right
    // there in the target dir.
    const src = try gradientRgba(a, 32, 32);
    defer a.free(src);
    const png = try encodePng(a, src, 32, 32);
    defer a.free(png);
    const default_path = try std.fs.path.join(a, &.{ work, default_icon_name });
    defer a.free(default_path);
    try cwd.writeFile(io, .{ .sub_path = default_path, .data = png });

    try testing.expectError(
        error.LauncherIconNotFound,
        stage(a, work, work, work, "art/nope.png"),
    );
}

test "stage fails loudly when app_icon is not a decodable PNG" {
    const a = testing.allocator;
    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();

    const work = ".zig-cache/launcher-icon-garbage";
    cwd.deleteTree(io, work) catch {};
    defer cwd.deleteTree(io, work) catch {};
    try cwd.createDirPath(io, work);
    const bogus = try std.fs.path.join(a, &.{ work, "icon.png" });
    defer a.free(bogus);
    try cwd.writeFile(io, .{ .sub_path = bogus, .data = "definitely not a png" });

    try testing.expectError(
        error.LauncherIconDecodeFailed,
        stage(a, work, work, work, "icon.png"),
    );
}

test "stage degrades to no icon when the assembler wrote no default" {
    const a = testing.allocator;
    const io = config.globalIo();
    const cwd = std.Io.Dir.cwd();

    const work = ".zig-cache/launcher-icon-none";
    cwd.deleteTree(io, work) catch {};
    defer cwd.deleteTree(io, work) catch {};
    try cwd.createDirPath(io, work);

    try testing.expect(!try stage(a, work, work, work, null));
    // Nothing staged means aapt must not be handed a `res/` tree.
    const res = try std.fs.path.join(a, &.{ work, res_subdir });
    defer a.free(res);
    try testing.expectError(error.FileNotFound, cwd.access(io, res, .{}));
}
