// ============================================================================
// Android Main Entry Point - Auto-generated by labelle CLI
// ============================================================================
// This file provides the Android-specific entry point using sokol with
// OpenGL ES 3.0 backend. It uses NativeActivity for a pure native app.
//
// The main game logic is imported from main.zig which contains:
// - Registries (Prefabs, Components, Scripts)
// - SceneLoader configuration
// - Initial scene
//
// Edit main.zig to add scenes, prefabs, and game logic.
// ============================================================================

const std = @import("std");
const engine = @import("labelle-engine");

// Sokol bindings - re-exported from engine
const sokol = engine.sokol;
const sg = sokol.gfx;
const sgl = sokol.gl;
const sapp = sokol.app;

// Import the main module with registries and scenes
const main = @import("main");

// Re-export types the main module needs
pub const Game = main.Game;
pub const Loader = main.Loader;
pub const initial_scene = main.initial_scene;

// ============================================================================
// Application State
// ============================================================================

const State = struct {
    allocator: std.mem.Allocator = undefined,
    game: ?*Game = null,
    scene: ?*engine.Scene = null,
    initialized: bool = false,
    frame_count: u32 = 0,
};

var state: State = .{};
var game_storage: Game = undefined;
var scene_storage: engine.Scene = undefined;

// ============================================================================
// Sokol Callbacks
// ============================================================================

export fn init() void {
    std.log.info("Initializing labelle-engine on Android", .{});

    sg.setup(.{
        .environment = sokol.glue.environment(),
        .logger = .{ .func = sokol.log.func },
    });

    sgl.setup(.{
        .logger = .{ .func = sokol.log.func },
    });

    state.allocator = std.heap.page_allocator;

    // Initialize game with embedded config
    game_storage = Game.init(state.allocator, .{
        .window = .{
            .width = @intCast(sapp.width()),
            .height = @intCast(sapp.height()),
            .title = "Labelle Game",
            .target_fps = 60,
        },
        .clear_color = .{ .r = 30, .g = 35, .b = 45 },
    }) catch |err| {
        std.log.err("Failed to initialize game: {}", .{err});
        sapp.quit();
        return;
    };
    state.game = &game_storage;
    state.game.?.fixPointers();

    const ctx = engine.SceneContext.init(state.game.?);

    Game.HookDispatcher.emit(.{ .scene_before_load = .{ .name = initial_scene.name, .allocator = state.allocator } });

    scene_storage = Loader.load(initial_scene, ctx) catch |err| {
        std.log.err("Failed to load scene: {}", .{err});
        sapp.quit();
        return;
    };
    state.scene = &scene_storage;

    Game.HookDispatcher.emit(.{ .scene_load = .{ .name = initial_scene.name } });

    state.initialized = true;
    std.log.info("Android backend initialized. Screen: {}x{}", .{ sapp.width(), sapp.height() });
}

export fn frame() void {
    if (!state.initialized or state.game == null or state.scene == null) return;

    state.frame_count += 1;

    const dt: f32 = @floatCast(sapp.frameDuration());

    // Update scene
    state.scene.?.update(dt);
    state.game.?.getPipeline().sync(state.game.?.getRegistry());

    // Render
    var pass_action: sg.PassAction = .{};
    pass_action.colors[0] = .{
        .load_action = .CLEAR,
        .clear_value = .{ .r = 0.118, .g = 0.137, .b = 0.176, .a = 1.0 },
    };
    sg.beginPass(.{
        .action = pass_action,
        .swapchain = sokol.glue.swapchain(),
    });

    const re = state.game.?.getRetainedEngine();
    re.beginFrame();
    re.render();
    re.endFrame();

    sg.endPass();
    sg.commit();
}

export fn cleanup() void {
    if (state.initialized and state.game != null) {
        if (state.game.?.getCurrentSceneName() == null) {
            Game.HookDispatcher.emit(.{ .scene_unload = .{ .name = initial_scene.name } });
        }
    }

    if (state.scene) |scene| {
        scene.deinit();
        state.scene = null;
    }

    if (state.game) |game| {
        game.deinit();
        state.game = null;
    }

    sgl.shutdown();
    sg.shutdown();

    std.log.info("Android backend cleanup complete.", .{});
}

export fn event(ev: ?*const sapp.Event) void {
    const e = ev orelse return;

    switch (e.type) {
        // Touch events
        .TOUCHES_BEGAN, .TOUCHES_MOVED, .TOUCHES_ENDED, .TOUCHES_CANCELLED => {
            // Forward to game input system
            if (state.game) |game| {
                _ = game;
                // TODO: game.handleTouchEvent(e);
            }
        },
        // Android back button (maps to ESCAPE)
        .KEY_DOWN => {
            if (e.key_code == .ESCAPE) {
                sapp.quit();
            }
        },
        // Lifecycle events
        .SUSPENDED => {
            std.log.info("App suspended (going to background)", .{});
        },
        .RESUMED => {
            std.log.info("App resumed (coming to foreground)", .{});
        },
        .QUIT_REQUESTED => {
            std.log.info("Quit requested", .{});
            sapp.quit();
        },
        else => {},
    }
}

// ============================================================================
// Main Entry Point
// ============================================================================

pub fn main() void {
    sapp.run(.{
        .init_cb = init,
        .frame_cb = frame,
        .cleanup_cb = cleanup,
        .event_cb = event,
        .width = 800,
        .height = 600,
        .window_title = "Labelle Game",
        .high_dpi = true,
        .fullscreen = true,
        .icon = .{ .sokol_default = true },
        .logger = .{ .func = sokol.log.func },
    });
}
