/// Generated by labelle-cli — do not edit.
const std = @import("std");
const engine = @import("labelle-engine");
const BackendGfx = @import("backend_gfx");
const BackendInput = @import("backend_input");
const BackendAudio = @import("backend_audio");
const window = @import("backend_window");
// Log sink (default: stderr). Override in project template to disable or customize.
const LogSink = engine.core.StderrLogSink;
const EcsAdapter = @import("ecs_backend");
const EcsBackend = EcsAdapter;
const GuiBackend = engine.StubGui;

// --- JSONC scene loaders (runtime) ---
const JsoncBridge = engine.JsoncSceneBridgeWithGizmos(AssembledGame, Components, Gizmos);
const jsonc_main_loader = struct {
    fn load(game: *AssembledGame) anyerror!void {
        return JsoncBridge.loadScene(game, "scenes/main.jsonc", "prefabs");
    }
}.load;
const jsonc_menu_loader = struct {
    fn load(game: *AssembledGame) anyerror!void {
        return JsoncBridge.loadScene(game, "scenes/menu.jsonc", "prefabs");
    }
}.load;
const jsonc_obstacles_loader = struct {
    fn load(game: *AssembledGame) anyerror!void {
        return JsoncBridge.loadScene(game, "scenes/obstacles.jsonc", "prefabs");
    }
}.load;

const gfx = @import("labelle-gfx");

const GameLayers = enum(u8) {
    background,
    world,
    ui,

    pub fn config(self: GameLayers) gfx.LayerConfig {
        return switch (self) {
            .background => .{ .order = 0, .space = .screen },
            .world => .{ .order = 1, .space = .world },
            .ui => .{ .order = 2, .space = .screen },
        };
    }
};

const ResourceRegistry = struct {
    pub const sprites = engine.ComptimeAtlas(@import("assets/sprites.json"));

    pub const textures = .{
        .sprites = "assets/sprites.png",
    };

    pub const names: [1][]const u8 = .{
        "sprites",
    };
};
const Resources = ResourceRegistry;

const AllHookPayloads = engine.HookPayload(EcsBackend.Entity);

const GameHooks = struct {};

const Renderer = gfx.GfxRenderer(BackendGfx, GameLayers, EcsBackend.Entity);

const AssembledGame = engine.GameConfig(
    Renderer,
    EcsBackend,
    BackendInput,
    BackendAudio,
    GuiBackend,
    *GameHooks,
    LogSink,
    Components,
    DiscoveredGizmoCategories,
);
const Prefabs = engine.PrefabRegistry(.{});

const Components = engine.ComponentRegistry(.{
    .Coin = @import("components/coin.zig").Coin,
    .Player = @import("components/player.zig").Player,
    .Score = @import("components/score.zig").Score,
    .Velocity = @import("components/velocity.zig").Velocity,
    .Wall = @import("components/wall.zig").Wall,
});

const GizmoCatEntry = struct { name: []const u8, id: u8 };
const DiscoveredGizmoCategories: []const GizmoCatEntry = &.{};

const AllScripts = struct {
    pub const scene_switcher = @import("scripts/scene_switcher.zig");
    pub const playing_01_player_movement = struct {
        const _inner = @import("scripts/playing/01_player_movement.zig");
        pub const game_states = .{
            "playing",
        };
        pub const tick = if (@hasDecl(_inner, "tick")) _inner.tick else {};
        pub const setup = if (@hasDecl(_inner, "setup")) _inner.setup else {};
        pub const drawGui = if (@hasDecl(_inner, "drawGui")) _inner.drawGui else {};
        pub const State = if (@hasDecl(_inner, "State")) _inner.State else {};
    };
    pub const playing_02_pause_check = struct {
        const _inner = @import("scripts/playing/02_pause_check.zig");
        pub const game_states = .{
            "playing",
        };
        pub const tick = if (@hasDecl(_inner, "tick")) _inner.tick else {};
        pub const setup = if (@hasDecl(_inner, "setup")) _inner.setup else {};
        pub const drawGui = if (@hasDecl(_inner, "drawGui")) _inner.drawGui else {};
        pub const State = if (@hasDecl(_inner, "State")) _inner.State else {};
    };
    pub const playing_paused_camera_control = struct {
        const _inner = @import("scripts/playing+paused/camera_control.zig");
        pub const game_states = .{
            "playing",
            "paused",
        };
        pub const tick = if (@hasDecl(_inner, "tick")) _inner.tick else {};
        pub const setup = if (@hasDecl(_inner, "setup")) _inner.setup else {};
        pub const drawGui = if (@hasDecl(_inner, "drawGui")) _inner.drawGui else {};
        pub const State = if (@hasDecl(_inner, "State")) _inner.State else {};
    };
    pub const menu_menu_system = struct {
        const _inner = @import("scripts/menu/menu_system.zig");
        pub const game_states = .{
            "menu",
        };
        pub const tick = if (@hasDecl(_inner, "tick")) _inner.tick else {};
        pub const setup = if (@hasDecl(_inner, "setup")) _inner.setup else {};
        pub const drawGui = if (@hasDecl(_inner, "drawGui")) _inner.drawGui else {};
        pub const State = if (@hasDecl(_inner, "State")) _inner.State else {};
    };
    pub const paused_unpause = struct {
        const _inner = @import("scripts/paused/unpause.zig");
        pub const game_states = .{
            "paused",
        };
        pub const tick = if (@hasDecl(_inner, "tick")) _inner.tick else {};
        pub const setup = if (@hasDecl(_inner, "setup")) _inner.setup else {};
        pub const drawGui = if (@hasDecl(_inner, "drawGui")) _inner.drawGui else {};
        pub const State = if (@hasDecl(_inner, "State")) _inner.State else {};
    };
};

const Scripts = engine.ScriptRegistry(AllScripts);

const GameContext = struct {};
const Runner = engine.ScriptRunner(AllScripts, GameContext, EcsBackend);

const Views = engine.EmptyViewRegistry;

const Gizmos = engine.GizmoRegistry(.{
    .coin = @import("gizmos/coin.zon"),
    .player = @import("gizmos/player.zon"),
});

// Gizmo rendering is now handled by g.renderGizmos() — no generated code needed.
// The engine delegates to the renderer's renderGizmoDraws() method.
const screen_w: u32 = 800;
const screen_h: u32 = 600;
const screen_title = "LaBelle v2 — Runtime Scenes Demo";
const target_fps: u32 = 60;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    window.initWindow(screen_w, screen_h, screen_title);
    defer window.closeWindow();
    window.setTargetFPS(target_fps);

    var hooks = GameHooks{};
    var g = AssembledGame.init(allocator);
    defer g.deinit();

    g.setHooks(&hooks);

    g.setScreenHeight(@as(f32, @floatFromInt(screen_h)));
    g.getCamera().setPosition(0, @as(f32, @floatFromInt(screen_h)));

    var runner = Runner.init(allocator, &g.active_world.ecs_backend);
    defer runner.deinit();


    // Runtime JSONC scenes
    g.registerSceneSimple("main", jsonc_main_loader);
    g.registerSceneSimple("menu", jsonc_menu_loader);
    g.registerSceneSimple("obstacles", jsonc_obstacles_loader);
    try g.setScene("main");
    g.setState("menu");

    // Load sprite atlases
    try g.loadAtlasFromMemory("sprites", @embedFile("assets/sprites.json"), @embedFile("assets/sprites.png"), ".png");

    runner.setup(&g);

    while (!window.windowShouldClose()) {
        const dt: f32 = 0.016;
        const scaled_dt = dt * g.time_scale;
        if (scaled_dt > 0) {
            runner.tick(&g, scaled_dt);
        }
        if (comptime @TypeOf(runner).profiling_enabled) {
            g.script_profile_ptr = @ptrCast(&runner.profile);
            g.script_profile_count = @TypeOf(runner).script_count;
        }
        g.tick(dt);

        window.beginDrawing();
        window.clearBackground(30, 30, 35, 255);
        g.render();
        g.renderGizmos();
        window.drawText(screen_title, 10, 10, 20, 180, 180, 180, 255);
        window.endDrawing();
    }
}
